// Calendrier de discipline — rythme : 3 soirs × 75 min + samedi 3h30 ≈ 7-9h/semaine

// ── Plan générique par module (commun à tous les profils) ───────────────────
export const MODULE_PLAN = [
  // Track ML & Data Science
  { id: "setup-pro",      track: "ml",  title: "Setup Pro",                   weeks: 2,  icon: "⚙️", priority: "A",   resource: "MIT Missing Semester",               project: "Repo template Git structuré" },
  { id: "python-ds",      track: "ml",  title: "Python pour la Data Science", weeks: 6,  icon: "🐍", priority: "A",   resource: "Kaggle Python + tutoriel officiel",  project: "CLI gestionnaire de données CSV" },
  { id: "sql",            track: "ml",  title: "SQL & Bases de données",      weeks: 4,  icon: "🗄", priority: "A",   resource: "SQLBolt + PostgreSQL Docs",          project: "Schéma BDD + 15 requêtes analytiques" },
  { id: "maths-ml",       track: "ml",  title: "Mathématiques pour le ML",    weeks: 6,  icon: "📐", priority: "A",   resource: "Mathematics for ML (Deisenroth)",    project: "Notebook : matrices, régression, gradient descent" },
  { id: "ml-classique",   track: "ml",  title: "Machine Learning classique",  weeks: 8,  icon: "🤖", priority: "A",   resource: "Google ML Crash Course + sklearn",   project: "Projet ML complet avec baseline et métriques" },
  { id: "deep-learning",  track: "ml",  title: "Deep Learning",               weeks: 5,  icon: "🧠", priority: "A",   resource: "PyTorch Tutorials + D2L.ai",         project: "Image classifier FashionMNIST/CIFAR" },
  { id: "nlp",            track: "ml",  title: "NLP & Transformers",          weeks: 4,  icon: "💬", priority: "A/B", resource: "HuggingFace Learn + Transformers docs",project: "Classificateur de texte fine-tuné" },
  { id: "mlops",          track: "ml",  title: "MLOps",                       weeks: 8,  icon: "⚙️", priority: "A",   resource: "MLflow + FastAPI + Docker",          project: "API /predict avec CI/CD et monitoring" },
  { id: "cloud-aws",      track: "ml",  title: "Cloud & AWS",                 weeks: 4,  icon: "☁️", priority: "A",   resource: "AWS Skill Builder",                  project: "Déploiement ML sur AWS EC2/Lambda" },
  // Track Web Full Stack
  { id: "html-css",       track: "web", title: "HTML & CSS",                  weeks: 3,  icon: "🎨", priority: "A",   resource: "MDN Web Docs",                       project: "Page portfolio responsive" },
  { id: "javascript",     track: "web", title: "JavaScript",                  weeks: 5,  icon: "⚡", priority: "A",   resource: "javascript.info",                    project: "Application web interactive" },
  { id: "react-nextjs",   track: "web", title: "React & Next.js",             weeks: 6,  icon: "⚛️", priority: "A",   resource: "react.dev + nextjs.org/docs",        project: "Site full-stack avec API routes" },
  { id: "backend-node",   track: "web", title: "Backend Node.js",             weeks: 4,  icon: "🟢", priority: "A",   resource: "Node.js docs + Express",             project: "API REST authentifiée" },
  { id: "databases-web",  track: "web", title: "Bases de données Web",        weeks: 3,  icon: "🗄", priority: "A",   resource: "Prisma + PostgreSQL",                project: "CRUD avec ORM et migrations" },
  { id: "deployment-web", track: "web", title: "Déploiement Web",             weeks: 2,  icon: "🚀", priority: "A",   resource: "Vercel + Docker Docs",               project: "App déployée avec CI/CD" },
];

export const TOTAL_WEEKS_ML  = MODULE_PLAN.filter(m => m.track === "ml").reduce((a, m) => a + m.weeks, 0);
export const TOTAL_WEEKS_WEB = MODULE_PLAN.filter(m => m.track === "web").reduce((a, m) => a + m.weeks, 0);

export const WEEKLY_SCHEDULE = [
  { day: "Lundi",    type: "study", sessions: [{ time: "19h00-20h15", label: "Leçon + exercices", duration: 75 }] },
  { day: "Mardi",    type: "rest",  sessions: [] },
  { day: "Mercredi", type: "study", sessions: [{ time: "19h00-20h15", label: "Leçon + exercices", duration: 75 }] },
  { day: "Jeudi",    type: "rest",  sessions: [] },
  { day: "Vendredi", type: "study", sessions: [{ time: "19h00-20h15", label: "Projet ou révision", duration: 75 }] },
  { day: "Samedi",   type: "deep",  sessions: [{ time: "09h00-12h30", label: "Projet portfolio ou nouveau module", duration: 210 }] },
  { day: "Dimanche", type: "rest",  sessions: [{ time: "20h00-20h30", label: "Révision légère (optionnel)", duration: 30 }] },
];

export const ROADMAP_5ANS = [
  {
    id: "phase1",
    period: "2026 — 2027",
    title: "Fondations & Portfolio",
    color: "from-emerald-500 to-teal-500",
    bgColor: "bg-emerald-500/10 border-emerald-500/30",
    textColor: "text-emerald-400",
    icon: "🌱",
    objective: "Construire des fondations solides et un portfolio GitHub visible",
    livrables: [
      "Environnement pro configuré (venv, Git, IDE)",
      "3 projets portfolio publiés sur GitHub",
      "1 API ML déployable avec Docker",
      "Certifications Kaggle (Python, Pandas, ML)",
    ],
    milestones: [
      { month: "Juil 2026", label: "Setup pro + Python fondamental" },
      { month: "Oct 2026",  label: "SQL + NumPy + Pandas maîtrisés" },
      { month: "Jan 2027",  label: "Projet ML classique terminé" },
      { month: "Avr 2027",  label: "Deep Learning + NLP terminés" },
      { month: "Juil 2027", label: "Capstone MLOps déployé sur AWS" },
    ],
  },
  {
    id: "phase2",
    period: "2027 — 2028",
    title: "Première entrée dans le domaine",
    color: "from-blue-500 to-indigo-500",
    bgColor: "bg-blue-500/10 border-blue-500/30",
    textColor: "text-blue-400",
    icon: "🚪",
    objective: "Entrer par ML Junior, MLOps Junior, Data Engineer ou Analytics Engineer",
    livrables: [
      "Expérience production réelle",
      "Réseau LinkedIn actif + candidatures ciblées",
      "AWS Cloud Practitioner obtenu",
    ],
    milestones: [
      { month: "Sept 2027", label: "Premières candidatures envoyées" },
      { month: "Jan 2028",  label: "Certification AWS obtenue" },
      { month: "Juil 2028", label: "Premier poste dans le domaine" },
    ],
    salaryTarget: "80 000 – 100 000 CAD",
  },
  {
    id: "phase3",
    period: "2028 — 2029",
    title: "Spécialisation Cloud/MLOps",
    color: "from-purple-500 to-violet-500",
    bgColor: "bg-purple-500/10 border-purple-500/30",
    textColor: "text-purple-400",
    icon: "⚡",
    objective: "Maîtriser le cloud avancé et commencer la robotique/Computer Vision",
    livrables: [
      "Projet cloud avancé (Kubernetes, Spark)",
      "Début ROS2 et Computer Vision avancé",
      "AWS Solutions Architect ou équivalent",
    ],
    milestones: [
      { month: "2028", label: "Kubernetes + pipelines Spark/Kafka" },
      { month: "2029", label: "ROS2 publisher/subscriber + RL CartPole" },
    ],
    salaryTarget: "95 000 – 115 000 CAD",
  },
  {
    id: "phase4",
    period: "2029 — 2030",
    title: "Master en IA / ML",
    color: "from-amber-500 to-orange-500",
    bgColor: "bg-amber-500/10 border-amber-500/30",
    textColor: "text-amber-400",
    icon: "🎓",
    objective: "M.Sc. ou M.Eng. en AI, ML, Computing Science, ECE ou Robotics",
    livrables: [
      "Admission dans un programme de Master",
      "Financement obtenu (bourse, RA, TA ou employeur)",
      "Projet de recherche appliqué",
    ],
    milestones: [
      { month: "2029", label: "Dossier d'admission préparé (GRE, lettre, portfolio)" },
      { month: "2030", label: "Master en cours + projet de recherche" },
    ],
  },
  {
    id: "phase5",
    period: "2030 — 2031",
    title: "Séniorisation & Leadership",
    color: "from-rose-500 to-pink-500",
    bgColor: "bg-rose-500/10 border-rose-500/30",
    textColor: "text-rose-400",
    icon: "👑",
    objective: "Leadership technique, architecture ML, mentoring, projets complexes",
    livrables: [
      "Rôle Senior ML Engineer ou Lead",
      "Architecture ML de production",
      "Mentoring d'équipe junior",
    ],
    milestones: [
      { month: "2031", label: "Senior ML Engineer / Lead confirmé" },
    ],
    salaryTarget: "120 000 – 160 000+ CAD",
  },
];

export const MONTHLY_PLAN_2026_2027 = [
  {
    month: "Juillet 2026",
    weeks: 2,
    priority: "A",
    bloc: "Setup pro",
    resource: "PyCharm Docs + MIT Missing Semester",
    project: "Repo template : src/, tests/, README, requirements.txt",
    validation: "Repo utilisable comme base pour tous les projets",
    color: "text-emerald-400",
  },
  {
    month: "Juillet–Août 2026",
    weeks: 6,
    priority: "A",
    bloc: "Python fondamental",
    resource: "Python Tutorial officiel + Kaggle Python",
    project: "CLI : gestionnaire de budget, fichiers CSV",
    validation: "CLI fonctionne, README clair, 10 commits propres",
    color: "text-emerald-400",
  },
  {
    month: "Août–Septembre 2026",
    weeks: 4,
    priority: "A",
    bloc: "Python avancé (OOP, tests)",
    resource: "Fluent Python (référence) + pytest docs",
    project: "Package Python structuré avec tests unitaires",
    validation: "Tests passent ; code en modules ; documentation",
    color: "text-emerald-400",
  },
  {
    month: "Septembre 2026",
    weeks: 4,
    priority: "A",
    bloc: "Git, Linux/Shell",
    resource: "Pro Git + MIT Missing Semester",
    project: "Script d'automatisation datasets",
    validation: "Workflow Git propre ; script reproductible",
    color: "text-emerald-400",
  },
  {
    month: "Octobre 2026",
    weeks: 4,
    priority: "A",
    bloc: "SQL + modélisation BDD",
    resource: "SQLBolt + PostgreSQL Docs",
    project: "Base 'répertoire santé' : 15 requêtes, export CSV",
    validation: "Schéma SQL propre + rapport court",
    color: "text-emerald-400",
  },
  {
    month: "Oct–Nov 2026",
    weeks: 5,
    priority: "A",
    bloc: "NumPy, Pandas, EDA, Visualisation",
    resource: "pandas docs + Kaggle Pandas",
    project: "EDA complet sur dataset public",
    validation: "Notebook propre + rapport 2 pages + graphiques",
    color: "text-emerald-400",
  },
  {
    month: "Nov–Déc 2026",
    weeks: 6,
    priority: "A",
    bloc: "Maths/stats pour ML",
    resource: "Mathematics for ML + OpenIntro Statistics",
    project: "Notebook 'Math for ML' : matrices, régression, gradient descent",
    validation: "Formules expliquées + implémentation sans scikit-learn",
    color: "text-emerald-400",
  },
  {
    month: "Déc 2026–Jan 2027",
    weeks: 8,
    priority: "A",
    bloc: "Machine Learning classique",
    resource: "Google ML Crash Course + scikit-learn Guide",
    project: "Projet ML #1 : régression/classification avec baseline",
    validation: "README pro, métriques, cross-validation, comparaison",
    color: "text-amber-400",
  },
  {
    month: "Février 2027",
    weeks: 5,
    priority: "A",
    bloc: "Deep Learning PyTorch",
    resource: "PyTorch Tutorials + D2L.ai",
    project: "Image classifier : FashionMNIST/CIFAR",
    validation: "Train/val/test ; modèle sauvegardé ; courbes ; inference",
    color: "text-amber-400",
  },
  {
    month: "Mars 2027",
    weeks: 4,
    priority: "A/B",
    bloc: "Computer Vision appliquée",
    resource: "PyTorch Transfer Learning + Ultralytics YOLO docs",
    project: "Détection ou classification sur images/vidéo",
    validation: "Démo courte, README, limites expliquées",
    color: "text-amber-400",
  },
  {
    month: "Avril 2027",
    weeks: 4,
    priority: "A/B",
    bloc: "NLP avec Hugging Face",
    resource: "HuggingFace Learn + Transformers docs",
    project: "Classificateur demandes santé francophone",
    validation: "Dataset propre ; modèle comparé à baseline ; prudence",
    color: "text-amber-400",
  },
  {
    month: "Mai–Juin 2027",
    weeks: 8,
    priority: "A",
    bloc: "MLOps : MLflow, FastAPI, Docker, CI/CD",
    resource: "MLflow + FastAPI + Docker + GitHub Actions Docs",
    project: "API /predict avec tracking MLflow et Docker",
    validation: "Tests auto, Dockerfile, endpoint fonctionnel",
    color: "text-rose-400",
  },
  {
    month: "Juin–Juil 2027",
    weeks: 4,
    priority: "A",
    bloc: "AWS débutant + Portfolio final",
    resource: "AWS Skill Builder + GitHub Actions",
    project: "Capstone : API ML déployable sur AWS, CV, LinkedIn",
    validation: "Lien démo ou screenshots, architecture, coûts estimés",
    color: "text-rose-400",
  },
];

export const ANTI_DECOURAGE_RULES = [
  {
    icon: "⏱",
    rule: "7-9h par semaine",
    detail: "3 soirs de 75 min + samedi 3h30. Pas plus — protège ton énergie et ta vie.",
  },
  {
    icon: "📅",
    rule: "Semaine tampon",
    detail: "La dernière semaine de chaque mois : corrections, README, repos. Pour rattraper sans culpabilité.",
  },
  {
    icon: "📚",
    rule: "1 ressource principale max",
    detail: "Choisir une ressource et aller jusqu'au bout. Pas de 'juste regarder' un autre cours.",
  },
  {
    icon: "🔨",
    rule: "1 livrable par bloc",
    detail: "Chaque apprentissage produit une trace GitHub visible. Pas de progrès sans preuve.",
  },
  {
    icon: "😴",
    rule: "Dimanche : repos protégé",
    detail: "Sauf révision légère de 30 min. La fatigue cumulative est l'ennemi n°1.",
  },
  {
    icon: "✂️",
    rule: "Règle anti-décrochage",
    detail: "Si fatigue > 2 semaines : retirer les options (bonus), jamais le cœur du programme.",
  },
];
