// Données de préparation aux certifications
// Inspiré de TutorialsDojo, A Cloud Guru, WhizLabs, ExamTopics

export const CERT_PREP = {
  "c1": {
    id: "c1",
    title: "Kaggle Python Certificate",
    provider: "Kaggle",
    duration: "3 semaines",
    difficulty: 2,
    icon: "🐍",
    color: "emerald",
    officialExamUrl: "https://www.kaggle.com/learn/python",
    studyPlan: [
      {
        week: 1,
        theme: "Fondations Python",
        hours: 6,
        objectives: [
          "Syntaxe Python : variables, types, conditions, boucles",
          "Fonctions : définition, arguments, *args/**kwargs, lambda",
          "Listes, tuples, dictionnaires, sets — opérations essentielles",
          "Compréhensions de listes et expressions générateurs",
        ],
        resources: [
          { label: "Kaggle Learn Python (cours officiel)", url: "https://www.kaggle.com/learn/python" },
          { label: "Python Tutorial officiel", url: "https://docs.python.org/3/tutorial/" },
        ],
        exercise: "Faire les 7 leçons Kaggle Python + tous les exercices intégrés",
      },
      {
        week: 2,
        theme: "Python intermédiaire",
        hours: 6,
        objectives: [
          "Gestion des erreurs : try/except/finally",
          "Modules et imports : os, sys, math, datetime",
          "Lecture/écriture de fichiers CSV et JSON",
          "Classes et programmation orientée objet (POO) basique",
        ],
        resources: [
          { label: "Real Python — OOP", url: "https://realpython.com/python3-object-oriented-programming/" },
          { label: "Automate the Boring Stuff (gratuit)", url: "https://automatetheboringstuff.com/" },
        ],
        exercise: "Écrire un script CLI qui lit un CSV, filtre des données et exporte le résultat",
      },
      {
        week: 3,
        theme: "Révision + examen blanc",
        hours: 5,
        objectives: [
          "Réviser les patterns récurrents des exercices Kaggle",
          "Faire 2 exercices Kaggle chronométrés (simulation examen)",
          "Revoir les erreurs commises et consolider",
          "Passer l'examen quand 3 exercices consécutifs sont parfaits",
        ],
        resources: [
          { label: "Kaggle Python exercises", url: "https://www.kaggle.com/learn/python" },
        ],
        exercise: "Mini-projet : script d'analyse d'un dataset CSV avec statistiques et export",
      },
    ],
    keyTopics: [
      "Syntaxe de base et types de données",
      "Fonctions et portée des variables",
      "Collections : list, dict, set, tuple",
      "Boucles et compréhensions",
      "Gestion des erreurs",
      "Modules stdlib courants",
      "Lecture/écriture fichiers",
      "Classes et héritage basique",
    ],
    tipsFromPeople: [
      "Fais TOUS les exercices du cours Kaggle, pas seulement lire — l'examen est pratique",
      "Entraîne-toi à écrire du code sans chercher sur Google avant de passer l'examen",
      "L'examen teste surtout les compréhensions de listes et les manipulations de dicts",
      "Si tu bloques plus de 5 min sur une question, passe à la suivante — reviens après",
    ],
    practiceQuestions: [
      {
        id: "c1q1",
        question: "Quelle est la sortie de ce code ?\n\nx = [1, 2, 3, 4, 5]\nprint([i**2 for i in x if i % 2 == 0])",
        options: ["[4, 16]", "[1, 4, 9, 16, 25]", "[2, 4]", "[4, 16, 25]"],
        answer: 0,
        explanation: "La compréhension filtre d'abord les nombres pairs (2, 4) puis élève au carré : 2²=4, 4²=16. Résultat : [4, 16].",
        difficulty: "facile",
      },
      {
        id: "c1q2",
        question: "Quelle différence entre une liste et un tuple en Python ?",
        options: [
          "Les tuples sont plus rapides mais immuables, les listes sont mutables",
          "Il n'y a pas de différence pratique",
          "Les listes ne peuvent contenir que des entiers",
          "Les tuples ne peuvent contenir que des chaînes",
        ],
        answer: 0,
        explanation: "Les tuples sont immuables (on ne peut pas les modifier après création) et légèrement plus rapides. Les listes sont mutables et peuvent être modifiées.",
        difficulty: "facile",
      },
      {
        id: "c1q3",
        question: "Comment attraper TOUTES les exceptions sauf KeyboardInterrupt ?",
        options: [
          "except Exception as e:",
          "except Error as e:",
          "except BaseException as e:",
          "except All as e:",
        ],
        answer: 0,
        explanation: "Exception est la classe de base de toutes les exceptions non-système. BaseException inclut aussi KeyboardInterrupt et SystemExit — à éviter en général.",
        difficulty: "moyen",
      },
      {
        id: "c1q4",
        question: "Quelle est la complexité temporelle de la recherche dans un set Python ?",
        options: ["O(1) en moyenne", "O(n)", "O(log n)", "O(n²)"],
        answer: 0,
        explanation: "Les sets utilisent une table de hachage. La recherche est O(1) en moyenne (O(n) dans le pire cas théorique, rare en pratique).",
        difficulty: "moyen",
      },
      {
        id: "c1q5",
        question: "Que retourne ce code ?\n\nd = {'a': 1, 'b': 2}\nprint(d.get('c', 0))",
        options: ["0", "None", "KeyError", "False"],
        answer: 0,
        explanation: "dict.get(key, default) retourne la valeur si la clé existe, sinon la valeur par défaut. Ici 'c' n'existe pas → retourne 0.",
        difficulty: "facile",
      },
    ],
    cheatsheet: [
      { category: "Listes", items: ["list.append(x)", "list.extend([1,2])", "list.pop(i)", "list.sort()", "list[::-1] # inverse"] },
      { category: "Dicts", items: ["d.get(k, default)", "d.items() / .keys() / .values()", "d.update({...})", "{k:v for k,v in d.items()}", "d.setdefault(k, [])"] },
      { category: "Strings", items: ["s.split(sep)", "sep.join(list)", "s.strip()", "s.replace(a,b)", "f'{var:.2f}' # f-string"] },
      { category: "Fichiers", items: ["with open('f.csv','r') as f:", "csv.reader(f)", "json.load(f)", "json.dump(data, f)", "f.readlines()"] },
    ],
  },

  "c3": {
    id: "c3",
    title: "Kaggle Intro to Machine Learning",
    provider: "Kaggle",
    duration: "4 semaines",
    difficulty: 3,
    icon: "🤖",
    color: "blue",
    officialExamUrl: "https://www.kaggle.com/learn/intro-to-machine-learning",
    studyPlan: [
      {
        week: 1,
        theme: "Concepts fondamentaux ML",
        hours: 7,
        objectives: [
          "Comprendre surapprentissage vs sous-apprentissage (bias-variance)",
          "Maîtriser train/validation/test split — pourquoi et comment",
          "Arbres de décision : critère de split, profondeur, pureté",
          "Random Forest : bagging, feature importance",
        ],
        resources: [
          { label: "Kaggle Intro to ML", url: "https://www.kaggle.com/learn/intro-to-machine-learning" },
          { label: "Google ML Crash Course", url: "https://developers.google.com/machine-learning/crash-course" },
        ],
        exercise: "Notebook Titanic : préparer les features et entraîner un premier modèle",
      },
      {
        week: 2,
        theme: "Sklearn en profondeur",
        hours: 8,
        objectives: [
          "Pipeline sklearn : Imputer → Encoder → Scaler → Model",
          "Encodage catégoriel : OneHotEncoder, OrdinalEncoder",
          "Métriques : accuracy, precision, recall, F1, ROC-AUC",
          "Cross-validation k-fold et StratifiedKFold",
        ],
        resources: [
          { label: "Sklearn documentation", url: "https://scikit-learn.org/stable/user_guide.html" },
          { label: "Kaggle Intermediate ML", url: "https://www.kaggle.com/learn/intermediate-machine-learning" },
        ],
        exercise: "Ajouter un Pipeline complet au notebook Titanic avec CV 5-fold",
      },
      {
        week: 3,
        theme: "Feature Engineering & XGBoost",
        hours: 8,
        objectives: [
          "Feature engineering : création de nouvelles variables pertinentes",
          "Gestion des valeurs manquantes : stratégies avancées",
          "XGBoost : hyperparamètres (n_estimators, max_depth, learning_rate)",
          "GridSearchCV et RandomizedSearchCV",
        ],
        resources: [
          { label: "Kaggle Feature Engineering", url: "https://www.kaggle.com/learn/feature-engineering" },
          { label: "XGBoost docs", url: "https://xgboost.readthedocs.io/" },
        ],
        exercise: "Compétition Kaggle Housing Prices : top 20% du classement",
      },
      {
        week: 4,
        theme: "Révision + examen blanc",
        hours: 6,
        objectives: [
          "Réviser tous les exercices Kaggle du cours",
          "Faire un notebook complet de A à Z sans aide",
          "Revoir les 10 erreurs les plus communes",
          "Passer la certification quand prêt",
        ],
        resources: [
          { label: "Kaggle Learn tous les cours", url: "https://www.kaggle.com/learn" },
        ],
        exercise: "Notebook autonome sur un dataset inédit : EDA → features → modèle → évaluation",
      },
    ],
    keyTopics: [
      "Arbres de décision et Random Forest",
      "Overfitting / Underfitting",
      "Train/Val/Test split",
      "Cross-validation",
      "Feature engineering",
      "Imputation des valeurs manquantes",
      "Encodage des variables catégorielles",
      "Métriques d'évaluation (accuracy, F1, AUC)",
      "XGBoost et hyperparamètres",
      "Pipeline sklearn",
    ],
    tipsFromPeople: [
      "L'examen Kaggle est pratique — tu dois soumettre un notebook fonctionnel",
      "Maîtrise le Pipeline sklearn par cœur, c'est incontournable",
      "Participe à au moins une compétition Kaggle avant l'examen pour l'expérience",
      "La mémorisation des métriques (quand utiliser F1 vs AUC) est testée",
      "Comprends le bias-variance tradeoff en profondeur, pas seulement la définition",
    ],
    practiceQuestions: [
      {
        id: "c3q1",
        question: "Ton modèle a 98% d'accuracy sur le train set et 62% sur le test set. Que se passe-t-il ?",
        options: [
          "Surapprentissage (overfitting) — le modèle mémorise les données d'entraînement",
          "Sous-apprentissage (underfitting) — le modèle est trop simple",
          "Le dataset est trop petit",
          "Il y a un data leak entre train et test",
        ],
        answer: 0,
        explanation: "Un écart important entre train accuracy (98%) et test accuracy (62%) indique un overfitting. Solutions : réduire la complexité du modèle, ajouter de la régularisation, plus de données.",
        difficulty: "facile",
      },
      {
        id: "c3q2",
        question: "Dans un problème de détection de fraude (1% de fraudes), quelle métrique privilégier ?",
        options: [
          "F1-score ou AUC-ROC (classes déséquilibrées)",
          "Accuracy (plus intuitive)",
          "MSE (standard)",
          "R² score",
        ],
        answer: 0,
        explanation: "Avec 1% de fraudes, un modèle qui prédit 'pas de fraude' toujours aurait 99% d'accuracy mais serait inutile. F1 et AUC-ROC tiennent compte des deux classes, même déséquilibrées.",
        difficulty: "moyen",
      },
      {
        id: "c3q3",
        question: "Quel est l'avantage principal d'un RandomForest vs un seul arbre de décision ?",
        options: [
          "Réduit la variance par bagging sur plusieurs arbres décorrélés",
          "Réduit le biais en utilisant plus de features",
          "Plus rapide à entraîner",
          "Fonctionne uniquement sur données numériques",
        ],
        answer: 0,
        explanation: "RandomForest utilise le bagging (Bootstrap Aggregating) : entraîne de nombreux arbres sur des sous-échantillons aléatoires et fait la moyenne des prédictions, réduisant la variance sans augmenter le biais.",
        difficulty: "moyen",
      },
      {
        id: "c3q4",
        question: "Comment gérer correctement les données catégorielles ordinales (ex: 'faible' < 'moyen' < 'fort') ?",
        options: [
          "OrdinalEncoder avec l'ordre défini explicitement",
          "OneHotEncoder (crée des colonnes binaires)",
          "LabelEncoder (automatique)",
          "Les supprimer — pas utilisables",
        ],
        answer: 0,
        explanation: "OrdinalEncoder avec l'ordre défini (categories=[['faible','moyen','fort']]) préserve la relation ordinale. OneHotEncoder perd l'ordre. LabelEncoder est pour les cibles, pas les features.",
        difficulty: "moyen",
      },
      {
        id: "c3q5",
        question: "Que fait cross_val_score(model, X, y, cv=5) ?",
        options: [
          "Divise le dataset en 5 plis, entraîne sur 4 et évalue sur 1 × 5 fois",
          "Entraîne le modèle 5 fois sur tout le dataset",
          "Crée 5 modèles différents avec des hyperparamètres différents",
          "Divise les données en 80/20 et répète 5 fois",
        ],
        answer: 0,
        explanation: "La cross-validation k-fold divise le dataset en k=5 plis égaux. À chaque itération, 1 pli sert de validation et les 4 autres d'entraînement. On obtient 5 scores → on prend la moyenne.",
        difficulty: "facile",
      },
    ],
    cheatsheet: [
      { category: "Pipeline sklearn", items: [
        "from sklearn.pipeline import Pipeline",
        "pipe = Pipeline([('imputer', SimpleImputer()), ('model', RandomForestClassifier())])",
        "pipe.fit(X_train, y_train)",
        "pipe.predict(X_test)",
      ]},
      { category: "Métriques", items: [
        "accuracy_score(y, ŷ) — classes équilibrées",
        "f1_score(y, ŷ, average='weighted') — déséquilibrées",
        "roc_auc_score(y, ŷ_proba) — probabilités",
        "confusion_matrix(y, ŷ)",
      ]},
      { category: "XGBoost", items: [
        "from xgboost import XGBClassifier",
        "model = XGBClassifier(n_estimators=100, max_depth=4, learning_rate=0.1)",
        "early_stopping_rounds=10 → évite overfitting",
        "model.feature_importances_",
      ]},
    ],
  },

  "c5": {
    id: "c5",
    title: "DeepLearning.AI — MLOps Specialization",
    provider: "DeepLearning.AI / Coursera",
    duration: "8 semaines",
    difficulty: 4,
    icon: "⚙️",
    color: "purple",
    officialExamUrl: "https://www.deeplearning.ai/courses/machine-learning-engineering-for-production-mlops/",
    studyPlan: [
      {
        week: 1,
        theme: "ML en production — vue d'ensemble",
        hours: 8,
        objectives: [
          "Comprendre le ML lifecycle complet (data → modèle → déploiement → monitoring)",
          "Data drift vs concept drift — définitions et détection",
          "Baseline models : pourquoi commencer simple",
          "Structurer un projet ML production-ready",
        ],
        resources: [
          { label: "Cours 1 : Introduction to Machine Learning in Production", url: "https://www.coursera.org/learn/introduction-to-machine-learning-in-production" },
          { label: "MLflow Docs", url: "https://mlflow.org/docs/latest/index.html" },
        ],
        exercise: "Convertir un notebook Jupyter en script Python modulaire avec logging",
      },
      {
        week: 2,
        theme: "Data Engineering pour ML",
        hours: 8,
        objectives: [
          "Feature stores : concept, Feast (open source)",
          "Validation de données : Great Expectations",
          "Data versioning : DVC (Data Version Control)",
          "Pipelines de données reproductibles",
        ],
        resources: [
          { label: "DVC Documentation", url: "https://dvc.org/doc" },
          { label: "Great Expectations", url: "https://greatexpectations.io/" },
        ],
        exercise: "Versionner un dataset avec DVC + ajouter des tests de validation de données",
      },
      {
        week: 3,
        theme: "Entraînement et expérimentation",
        hours: 8,
        objectives: [
          "Experiment tracking avec MLflow : paramètres, métriques, artefacts",
          "Hyperparameter tuning : Optuna vs GridSearch",
          "Distributed training basics (PyTorch DDP)",
          "Reproductibilité : seeds, environnements, configs",
        ],
        resources: [
          { label: "MLflow Tracking", url: "https://mlflow.org/docs/latest/tracking.html" },
          { label: "Optuna Docs", url: "https://optuna.readthedocs.io/" },
        ],
        exercise: "Experiment MLflow avec 5 configurations différentes + comparaison visuelle",
      },
      {
        week: 4,
        theme: "Déploiement avec FastAPI + Docker",
        hours: 9,
        objectives: [
          "Créer une API ML avec FastAPI (predict endpoint)",
          "Dockeriser l'API : Dockerfile, docker build, docker run",
          "Pousser sur Docker Hub ou ECR",
          "Health checks et gestion des erreurs dans l'API",
        ],
        resources: [
          { label: "FastAPI Docs", url: "https://fastapi.tiangolo.com/" },
          { label: "Docker Getting Started", url: "https://docs.docker.com/get-started/" },
        ],
        exercise: "API FastAPI complète : /predict, /health, /metrics — dockerisée et testée",
      },
      {
        week: 5,
        theme: "AWS pour ML",
        hours: 9,
        objectives: [
          "S3 : stockage de datasets et modèles",
          "EC2 : déploiement d'une API ML sur instance",
          "Lambda : inference serverless pour cas simples",
          "SageMaker basics : training jobs et endpoints",
        ],
        resources: [
          { label: "AWS Skill Builder (gratuit)", url: "https://skillbuilder.aws/" },
          { label: "SageMaker Documentation", url: "https://docs.aws.amazon.com/sagemaker/" },
        ],
        exercise: "Déployer l'API Docker sur EC2 avec HTTPS via Nginx",
      },
      {
        week: 6,
        theme: "CI/CD pour ML",
        hours: 8,
        objectives: [
          "GitHub Actions : workflow test → build → deploy",
          "Tests automatiques pour modèles ML (performance regression)",
          "Semantic versioning des modèles",
          "Blue/Green deployment pour les APIs ML",
        ],
        resources: [
          { label: "GitHub Actions Docs", url: "https://docs.github.com/en/actions" },
          { label: "Cours 3 MLOps DeepLearning.AI", url: "https://www.coursera.org/learn/mlops-fundamentals" },
        ],
        exercise: "Pipeline CI/CD complet : push → tests → build Docker → déploiement automatique",
      },
      {
        week: 7,
        theme: "Monitoring et observabilité",
        hours: 8,
        objectives: [
          "Monitoring de modèle : drift détection avec Evidently AI",
          "Logs structurés : JSON, niveaux, alertes",
          "Métriques applicatives : latence P50/P95/P99, throughput",
          "Retraining triggers : quand et comment",
        ],
        resources: [
          { label: "Evidently AI Docs", url: "https://docs.evidentlyai.com/" },
          { label: "Cours 4 : Deploying ML Models in Production", url: "https://www.coursera.org/learn/deploying-machine-learning-models-in-production" },
        ],
        exercise: "Dashboard Evidently : rapport hebdomadaire automatique de drift",
      },
      {
        week: 8,
        theme: "Révision + projet final",
        hours: 10,
        objectives: [
          "Réviser tous les concepts des 7 semaines",
          "Projet final : pipeline ML end-to-end complet",
          "Documenter l'architecture et les choix techniques",
          "Passer la certification",
        ],
        resources: [
          { label: "MLOps Community", url: "https://mlops.community/" },
        ],
        exercise: "Livrer un système ML complet : data → entraînement → API → monitoring → CI/CD",
      },
    ],
    keyTopics: [
      "ML Lifecycle complet",
      "Data drift et concept drift",
      "FastAPI pour servir des modèles",
      "Docker et conteneurisation",
      "MLflow (experiment tracking)",
      "CI/CD avec GitHub Actions",
      "AWS S3, EC2, Lambda, SageMaker",
      "Monitoring avec Evidently AI",
      "Feature stores",
      "DVC (data versioning)",
    ],
    tipsFromPeople: [
      "Faire le projet capstone de chaque cours — c'est là que l'apprentissage se fixe",
      "Monter l'infrastructure toi-même avant de regarder les corrections",
      "MLflow + FastAPI + Docker sont les trois outils à maîtriser en priorité",
      "Le cours peut s'auditer gratuitement sur Coursera — fais le pour les vidéos + prends la cert quand tu as pratiqué",
      "Commence par déployer sur ton ordi local avant de passer au cloud",
    ],
    practiceQuestions: [
      {
        id: "c5q1",
        question: "Quelle est la différence entre data drift et concept drift ?",
        options: [
          "Data drift : la distribution des inputs change. Concept drift : la relation entre X et Y change.",
          "Data drift : le modèle overfitte. Concept drift : le modèle underfitte.",
          "Ils sont synonymes — les deux désignent une dégradation du modèle.",
          "Data drift : les données manquantes augmentent. Concept drift : les labels changent de format.",
        ],
        answer: 0,
        explanation: "Data drift (ou feature drift) : les distributions des variables d'entrée changent (ex: l'âge moyen des clients augmente). Concept drift : la relation statistique entre X et Y change (ex: un comportement qui était frauduleux ne l'est plus). Les deux nécessitent un retraining.",
        difficulty: "moyen",
      },
      {
        id: "c5q2",
        question: "Pourquoi containeriser une API ML avec Docker ?",
        options: [
          "Reproductibilité : l'environnement exact (Python, librairies) est encapsulé et déployable partout",
          "Pour augmenter la vitesse d'inférence du modèle",
          "Docker est obligatoire pour utiliser AWS",
          "Pour éviter d'avoir à écrire des tests unitaires",
        ],
        answer: 0,
        explanation: "Docker garantit que l'application tourne identiquement en développement, staging et production. Cela élimine le 'ça marche sur ma machine'. Les dépendances exactes sont figées dans l'image.",
        difficulty: "facile",
      },
      {
        id: "c5q3",
        question: "Dans une architecture MLOps, à quel moment doit-on déclencher un retraining ?",
        options: [
          "Quand les métriques de performance (drift, accuracy) dépassent un seuil défini",
          "À heure fixe chaque semaine, peu importe les métriques",
          "Seulement quand l'équipe remarque une dégradation manuelle",
          "Jamais — un bon modèle ne se dégrade pas",
        ],
        answer: 0,
        explanation: "Le retraining automatique se déclenche sur des seuils : drift détecté, accuracy < seuil, ou volume de nouvelles données suffisant. Le retraining calendaire fixe est un anti-pattern — on retraine même si inutile.",
        difficulty: "moyen",
      },
      {
        id: "c5q4",
        question: "Quelle est la différence entre P50 et P99 en monitoring de latence ?",
        options: [
          "P50 = latence médiane (50% des requêtes plus rapides), P99 = 99% des requêtes sont sous ce seuil",
          "P50 = 50ms de latence moyenne, P99 = 99ms de latence maximale",
          "P50 et P99 sont des métriques de précision du modèle",
          "P99 est la latence en production, P50 en développement",
        ],
        answer: 0,
        explanation: "Les percentiles de latence décrivent la distribution : P50 = médiane (la moitié des requêtes sont plus rapides). P99 = 99% des requêtes sont traitées sous ce délai. P99 détecte les pics de latence que la moyenne masque.",
        difficulty: "moyen",
      },
      {
        id: "c5q5",
        question: "Pourquoi tracker les expériences ML avec MLflow plutôt que des notes manuelles ?",
        options: [
          "Reproductibilité complète : paramètres, métriques, artefacts et code versionnés automatiquement",
          "MLflow est obligatoire pour déployer sur AWS SageMaker",
          "Pour éviter d'écrire de la documentation",
          "Parce que les notebooks Jupyter ne peuvent pas logger de métriques",
        ],
        answer: 0,
        explanation: "MLflow enregistre automatiquement chaque run : hyperparamètres, métriques par epoch, artefacts (modèle, graphes). L'interface web permet de comparer visuellement toutes les expériences et de reproduire n'importe quel run passé.",
        difficulty: "facile",
      },
    ],
    cheatsheet: [
      { category: "MLflow", items: [
        "mlflow.start_run()",
        "mlflow.log_param('lr', 0.01)",
        "mlflow.log_metric('accuracy', 0.94)",
        "mlflow.sklearn.log_model(model, 'model')",
        "mlflow ui  # dashboard local",
      ]},
      { category: "FastAPI ML", items: [
        "from fastapi import FastAPI",
        "app = FastAPI()",
        "@app.post('/predict') async def predict(data: InputData):",
        "model = joblib.load('model.pkl')",
        "return {'prediction': model.predict([data.features])[0]}",
      ]},
      { category: "Docker", items: [
        "FROM python:3.11-slim",
        "COPY requirements.txt . && pip install -r requirements.txt",
        "COPY . .",
        "CMD ['uvicorn', 'main:app', '--host', '0.0.0.0']",
        "docker build -t mon-api . && docker run -p 8000:8000 mon-api",
      ]},
    ],
  },

  "c6": {
    id: "c6",
    title: "AWS Cloud Practitioner (CLF-C02)",
    provider: "Amazon Web Services",
    duration: "6 semaines",
    difficulty: 3,
    icon: "☁️",
    color: "amber",
    officialExamUrl: "https://aws.amazon.com/certification/certified-cloud-practitioner/",
    studyPlan: [
      {
        week: 1,
        theme: "Cloud & AWS Fundamentals",
        hours: 7,
        objectives: [
          "Modèles cloud : IaaS, PaaS, SaaS — exemples concrets",
          "Avantages du cloud : elasticité, pay-as-you-go, global reach",
          "Régions AWS, Zones de disponibilité, Edge Locations",
          "Modèle de responsabilité partagée AWS",
        ],
        resources: [
          { label: "AWS Cloud Practitioner Essentials (gratuit)", url: "https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials" },
          { label: "AWS Well-Architected Framework", url: "https://aws.amazon.com/architecture/well-architected/" },
        ],
        exercise: "Créer un compte AWS Free Tier, explorer la console, créer un bucket S3",
      },
      {
        week: 2,
        theme: "Services Core AWS",
        hours: 8,
        objectives: [
          "Compute : EC2 (types, pricing), Lambda (serverless), ECS/EKS",
          "Storage : S3 (classes), EBS, EFS, Glacier",
          "Database : RDS, DynamoDB, Aurora, ElastiCache",
          "Network : VPC, Subnets, Security Groups, Route 53",
        ],
        resources: [
          { label: "AWS Skill Builder — services overview", url: "https://skillbuilder.aws/" },
          { label: "AWS Free Tier — pratiquer", url: "https://aws.amazon.com/free/" },
        ],
        exercise: "Lancer une instance EC2, y déployer une app simple, configurer Security Group",
      },
      {
        week: 3,
        theme: "Sécurité & IAM",
        hours: 7,
        objectives: [
          "IAM : Users, Groups, Roles, Policies — least privilege",
          "MFA, Access Keys, AWS Organizations",
          "Services de sécurité : Shield, WAF, GuardDuty, Inspector",
          "Conformité : AWS Artifact, programmes de conformité",
        ],
        resources: [
          { label: "AWS IAM Docs", url: "https://docs.aws.amazon.com/iam/" },
          { label: "AWS Security Best Practices", url: "https://aws.amazon.com/security/security-resources/" },
        ],
        exercise: "Créer un utilisateur IAM avec politique minimale, activer MFA sur root account",
      },
      {
        week: 4,
        theme: "Pricing & Support",
        hours: 6,
        objectives: [
          "Modèles de pricing : On-Demand, Reserved, Spot, Savings Plans",
          "AWS Pricing Calculator, Cost Explorer, Budgets",
          "Plans de support : Basic, Developer, Business, Enterprise",
          "AWS Trusted Advisor — catégories et recommandations",
        ],
        resources: [
          { label: "AWS Pricing Calculator", url: "https://calculator.aws/pricing/2/home" },
          { label: "AWS Total Cost of Ownership", url: "https://aws.amazon.com/tco-calculator/" },
        ],
        exercise: "Estimer le coût mensuel d'une architecture simple avec Pricing Calculator",
      },
      {
        week: 5,
        theme: "Architecture cloud & services supplémentaires",
        hours: 7,
        objectives: [
          "Well-Architected : 6 pilliers (opexcellence, sécurité, fiabilité, perf, coût, durabilité)",
          "CloudFront (CDN), SQS, SNS, EventBridge",
          "Monitoring : CloudWatch métriques et alertes",
          "Migration : services AWS Migration Hub, Snowball",
        ],
        resources: [
          { label: "AWS Architecture Center", url: "https://aws.amazon.com/architecture/" },
        ],
        exercise: "Configurer une alarme CloudWatch sur la facturation (alerte > 10$)",
      },
      {
        week: 6,
        theme: "Révision intensive + examens blancs",
        hours: 9,
        objectives: [
          "Faire 3 examens blancs complets (65 questions chacun)",
          "Analyser chaque erreur et revoir le service correspondant",
          "Flashcards sur les services les moins mémorisés",
          "Passer l'examen dès que tu obtiens 85%+ sur les blancs",
        ],
        resources: [
          { label: "AWS Official Practice Exam (gratuit via Skill Builder)", url: "https://explore.skillbuilder.aws/learn/course/external/view/elearning/9153/aws-certified-cloud-practitioner-official-practice-question-set-clf-c02-english" },
          { label: "TutorialsDojo CLF-C02 cheat sheets", url: "https://tutorialsdojo.com/aws-cheat-sheets/" },
        ],
        exercise: "3 examens blancs + révision ciblée des sujets faibles",
      },
    ],
    keyTopics: [
      "Modèle de responsabilité partagée",
      "Régions, AZ, Edge Locations",
      "EC2 : types et pricing models",
      "S3 : classes de stockage",
      "IAM : Users, Roles, Policies",
      "VPC et Security Groups",
      "RDS vs DynamoDB",
      "Lambda (serverless)",
      "CloudWatch monitoring",
      "6 pilliers Well-Architected",
      "Pricing : On-Demand vs Reserved vs Spot",
      "Plans de support AWS",
    ],
    tipsFromPeople: [
      "TutorialsDojo a les meilleurs examens blancs — fais-en 3 avant de passer le vrai",
      "L'examen CLF-C02 a 65 questions en 90 minutes — gère ton temps (1 min 20 par question)",
      "Le modèle de responsabilité partagée revient dans 30% des questions minimum",
      "Mémorise les différences clés : SQS vs SNS, RDS vs DynamoDB, Security Group vs NACL",
      "Si tu as pratiqué AWS (déployé une app), le cours théorique ira 2x plus vite",
      "Score de passage : 700/1000 — vise 800+ sur les blancs avant de t'inscrire",
    ],
    practiceQuestions: [
      {
        id: "c6q1",
        question: "Selon le modèle de responsabilité partagée AWS, qui est responsable de la sécurité du système d'exploitation d'une instance EC2 ?",
        options: [
          "Le client (c'est une responsabilité 'dans' le cloud)",
          "AWS (c'est une responsabilité 'du' cloud)",
          "Partagée à 50/50 entre AWS et le client",
          "Dépend du type d'instance EC2 choisi",
        ],
        answer: 0,
        explanation: "AWS est responsable DE la sécurité du cloud (infrastructure physique, hyperviseur). Le client est responsable DANS le cloud : OS, applications, données, IAM, réseau VPC. Le patching de l'OS sur EC2 est donc la responsabilité du client.",
        difficulty: "moyen",
      },
      {
        id: "c6q2",
        question: "Quelle option EC2 est la moins chère pour une charge de travail interruptible qui peut reprendre ?",
        options: [
          "Spot Instances — jusqu'à 90% moins cher que On-Demand",
          "Reserved Instances — 72% moins cher avec engagement 1 an",
          "On-Demand — plus de flexibilité",
          "Dedicated Hosts — isolation matérielle",
        ],
        answer: 0,
        explanation: "Les Spot Instances utilisent la capacité EC2 non utilisée — jusqu'à 90% moins cher que On-Demand. En contrepartie, AWS peut récupérer l'instance avec 2 minutes de préavis. Idéal pour : traitement par lots, ML training, rendering.",
        difficulty: "facile",
      },
      {
        id: "c6q3",
        question: "Quelle classe de stockage S3 est optimale pour des données accédées une fois par mois et qui doivent être disponibles rapidement ?",
        options: [
          "S3 Standard-IA (Infrequent Access)",
          "S3 Standard",
          "S3 Glacier Instant Retrieval",
          "S3 One Zone-IA",
        ],
        answer: 0,
        explanation: "S3 Standard-IA est conçu pour les données accédées peu fréquemment mais qui nécessitent un accès rapide quand nécessaire. Moins cher que Standard en stockage, mais avec des frais de récupération. S3 Glacier a des délais de récupération de minutes à heures.",
        difficulty: "moyen",
      },
      {
        id: "c6q4",
        question: "Quelle est la différence entre un Security Group et un Network ACL (NACL) dans AWS VPC ?",
        options: [
          "Security Group : stateful, niveau instance. NACL : stateless, niveau subnet",
          "Security Group : niveau subnet. NACL : niveau instance",
          "Ils sont identiques, juste différents noms",
          "Security Group : uniquement pour le trafic entrant. NACL : uniquement sortant",
        ],
        answer: 0,
        explanation: "Security Group est stateful (si tu autorises le trafic entrant, la réponse sort automatiquement) et s'applique à une instance. NACL est stateless (règles séparées entrée/sortie) et s'applique à un subnet entier. En pratique, on utilise principalement les Security Groups.",
        difficulty: "difficile",
      },
      {
        id: "c6q5",
        question: "Un client veut réduire ses coûts AWS sur des instances EC2 utilisées 24/7 depuis 1 an. Quelle option recommander ?",
        options: [
          "Reserved Instances (1 an) — jusqu'à 72% d'économies vs On-Demand",
          "Spot Instances — le moins cher",
          "On-Demand — pas de changement",
          "Dedicated Hosts — meilleur pour l'utilisation continue",
        ],
        answer: 0,
        explanation: "Pour des charges continues (24/7), les Reserved Instances avec engagement 1 an offrent jusqu'à 72% d'économies. Les Spot peuvent être interrompues (pas adapté 24/7). Savings Plans offrent encore plus de flexibilité avec des économies similaires.",
        difficulty: "moyen",
      },
    ],
    cheatsheet: [
      { category: "Services Compute", items: [
        "EC2 : VM cloud — types: t3, m5, c5, r5, p3 (GPU ML)",
        "Lambda : serverless, max 15min, 10GB RAM",
        "ECS/EKS : containers Docker/Kubernetes",
        "Elastic Beanstalk : PaaS (déploiement simplifié)",
      ]},
      { category: "Stockage", items: [
        "S3 Standard : fréquent (>1x/mois)",
        "S3 Standard-IA : peu fréquent, accès rapide",
        "S3 Glacier : archive, récupération minutes-heures",
        "EBS : disque pour EC2 (bloc storage)",
        "EFS : NFS partagé entre instances",
      ]},
      { category: "Sécurité", items: [
        "IAM = Users + Groups + Roles + Policies",
        "Principle of Least Privilege (droit minimum)",
        "MFA obligatoire sur root account",
        "Security Group = stateful + niveau instance",
        "NACL = stateless + niveau subnet",
      ]},
    ],
  },
};

export const CERT_PREP_LIST = Object.values(CERT_PREP);

export function getCertPrep(certId) {
  return CERT_PREP[certId] || null;
}
