// ─────────────────────────────────────────────────────────────────────────────
// RÈGLE IA — TRÈS IMPORTANTE
// Le tuteur AI NE DOIT JAMAIS faire le projet à la place de l'apprenant.
// Si on lui demande du code complet : expliquer gentiment comment réfléchir,
// quelle ressource lire, quelle question se poser. Guider, jamais faire.
// ─────────────────────────────────────────────────────────────────────────────

// hint_level : "high" = débutant (beaucoup d'aide), "medium" = intermédiaire, "none" = avancé
// track : "ml" | "web" | "pmp"

export const PROJECTS = [

  // ══════════════════════════════════════════════════════════════════════════
  // ML — DÉBUTANT — 6 projets
  // ══════════════════════════════════════════════════════════════════════════
  {
    track: "ml",
    id: "p-deb-1",
    title: "Analyseur de notes de classe",
    level: "debutant",
    hint_level: "high",
    duration: "1 semaine",
    icon: "📊",
    skills: ["Python", "pandas", "matplotlib", "statistiques descriptives"],
    description: "Charge un fichier CSV de notes d'étudiants, calcule les statistiques (moyenne, médiane, écart-type), identifie les élèves en difficulté et produit un rapport visuel.",
    learning_goal: "Apprendre à manipuler des données tabulaires, calculer des statistiques et créer une visualisation utile.",
    steps: [
      "Crée un CSV fictif avec 20 étudiants et 5 matières",
      "Charge le fichier avec pandas et explore-le (head, describe, info)",
      "Calcule la moyenne par étudiant et par matière",
      "Identifie les étudiants sous la barre des 60%",
      "Crée un histogramme des moyennes avec matplotlib",
      "Génère un rapport texte avec les statistiques clés",
    ],
    hints: [
      {
        step: 0,
        title: "Comment créer ton CSV ?",
        hint: "Tu peux créer un fichier CSV manuellement dans Excel ou avec Python. Pense à tes colonnes : Nom, Math, Français, Science, Histoire, Anglais. La fonction pd.DataFrame() peut aussi générer des données de test avec des valeurs aléatoires (cherche np.random.randint).",
      },
      {
        step: 1,
        title: "Explorer un DataFrame",
        hint: "Un DataFrame pandas a des méthodes très utiles : .head() pour voir les premières lignes, .info() pour les types de colonnes, .describe() pour les statistiques automatiques. Essaie-les une par une et lis ce que chacune affiche.",
      },
      {
        step: 2,
        title: "Calculer des moyennes",
        hint: "Pandas a une méthode .mean() qui calcule la moyenne d'une colonne ou d'une ligne. Pour calculer la moyenne par étudiant (ligne), pense à l'argument axis=. Consulte la doc : pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html",
      },
      {
        step: 3,
        title: "Filtrer des lignes selon une condition",
        hint: "En pandas, on filtre avec des conditions booléennes entre crochets : df[df['colonne'] < valeur]. C'est comme dire 'garde seulement les lignes où la condition est vraie'. Essaie d'abord avec une seule condition simple.",
      },
      {
        step: 4,
        title: "Créer un histogramme",
        hint: "matplotlib.pyplot.hist() crée un histogramme. Commence par import matplotlib.pyplot as plt, puis plt.hist(tes_données), plt.show(). Cherche comment ajouter un titre et des labels aux axes — c'est dans plt.title(), plt.xlabel().",
      },
      {
        step: 5,
        title: "Générer un rapport texte",
        hint: "Tu peux simplement écrire du texte formaté avec print() et des f-strings. Pour sauvegarder dans un fichier texte, utilise open('rapport.txt', 'w') as f: et f.write(). Pense à inclure : nombre d'étudiants, moyenne générale, meilleure/pire matière.",
      },
    ],
    resources: [
      { label: "pandas getting started", url: "https://pandas.pydata.org/docs/getting_started/index.html" },
      { label: "matplotlib tutorials", url: "https://matplotlib.org/stable/tutorials/index.html" },
    ],
    ai_guidance: "Si tu bloques, demande au tuteur de t'expliquer le concept qui te pose problème — pas de te donner le code. Ex: 'Explique-moi comment fonctionne le filtrage pandas' plutôt que 'Écris le code pour filtrer'.",
  },

  {
    track: "ml",
    id: "p-deb-2",
    title: "Prédicteur de prix de maison (régression simple)",
    level: "debutant",
    hint_level: "high",
    duration: "1 semaine",
    icon: "🏠",
    skills: ["Python", "scikit-learn", "pandas", "LinearRegression"],
    description: "Entraîne un modèle de régression linéaire pour prédire le prix d'une maison à partir de sa superficie. Visualise la droite de régression et évalue l'erreur.",
    learning_goal: "Comprendre le concept fondamental de régression linéaire, d'entraînement d'un modèle et d'évaluation.",
    steps: [
      "Crée ou télécharge un dataset superficie → prix (50-100 maisons)",
      "Explore les données : scatter plot superficie vs prix",
      "Sépare les données en train (80%) et test (20%)",
      "Entraîne un LinearRegression de scikit-learn sur le train",
      "Prédit les prix du test set et trace la droite de régression",
      "Calcule le MSE et le R² pour évaluer ton modèle",
    ],
    hints: [
      {
        step: 0,
        title: "Où trouver un dataset simple ?",
        hint: "Tu peux générer tes propres données avec numpy : superficie = np.random.uniform(50, 300, 100) et prix = superficie * 3000 + np.random.normal(0, 20000, 100). Ou télécharge le dataset 'Housing' sur Kaggle. L'important c'est de comprendre la structure : une colonne X (superficie) et une colonne y (prix).",
      },
      {
        step: 1,
        title: "Visualiser avec scatter plot",
        hint: "plt.scatter(X, y) trace un nuage de points. Regarde si tu vois une tendance linéaire — c'est ce que la régression va modéliser. Ajoute plt.xlabel('Superficie (m²)') et plt.ylabel('Prix ($)') pour rendre le graphique lisible.",
      },
      {
        step: 2,
        title: "Train/Test split",
        hint: "sklearn a une fonction toute faite : from sklearn.model_selection import train_test_split. Elle prend (X, y, test_size=0.2, random_state=42). Le random_state fixe le hasard pour que tu obtiens les mêmes résultats à chaque exécution.",
      },
      {
        step: 3,
        title: "Entraîner LinearRegression",
        hint: "from sklearn.linear_model import LinearRegression, puis model = LinearRegression(), puis model.fit(X_train, y_train). ATTENTION : sklearn attend des tableaux 2D pour X. Si tu as une seule colonne, reshape avec X.reshape(-1, 1).",
      },
      {
        step: 4,
        title: "Tracer la droite de régression",
        hint: "Après model.fit(), model.predict() donne les prédictions. Pour tracer la droite : plt.scatter(X_test, y_test) puis plt.plot(X_test, model.predict(X_test.reshape(-1,1)), color='red'). La droite rouge montre ce que ton modèle prédit.",
      },
      {
        step: 5,
        title: "MSE et R² — que signifient-ils ?",
        hint: "MSE (Mean Squared Error) mesure l'erreur moyenne au carré — plus c'est bas, mieux c'est. R² (coefficient de détermination) va de 0 à 1 — 1 = modèle parfait. sklearn les calcule avec mean_squared_error() et r2_score() dans sklearn.metrics. Cherche comment les importer et les utiliser.",
      },
    ],
    resources: [
      { label: "sklearn Linear Regression", url: "https://scikit-learn.org/stable/modules/linear_model.html" },
      { label: "Kaggle Housing dataset", url: "https://www.kaggle.com/datasets/harlfoxem/housesalesprediction" },
    ],
    ai_guidance: "Le tuteur peut t'expliquer pourquoi on utilise reshape(-1, 1), ce que signifie R², ou comment interpréter ton graphique. Il ne t'écrira pas le code — c'est toi qui apprends.",
  },

  {
    track: "ml",
    id: "p-deb-3",
    title: "Classificateur de spam email",
    level: "debutant",
    hint_level: "high",
    duration: "1-2 semaines",
    icon: "📧",
    skills: ["Python", "pandas", "scikit-learn", "NLP basique", "Naive Bayes"],
    description: "Construis un classificateur qui détecte si un email est spam ou non à partir de son texte. Utilise le dataset SMS Spam Collection de UCI.",
    learning_goal: "Introduire le NLP basique (bag of words, TF-IDF) et la classification de texte.",
    steps: [
      "Télécharge le dataset SMS Spam Collection (UCI / Kaggle)",
      "Explore les données : ratio spam/ham, longueur des messages",
      "Nettoie le texte : minuscules, suppression ponctuation",
      "Transforme le texte en vecteurs avec CountVectorizer ou TfidfVectorizer",
      "Entraîne un Naive Bayes (MultinomialNB) et évalue avec F1-score",
      "Teste ton modèle sur 3 messages que tu écris toi-même",
    ],
    hints: [
      { step: 0, title: "Télécharger le dataset", hint: "Cherche 'SMS Spam Collection UCI' sur Kaggle ou sur le site UCI Machine Learning Repository. C'est un fichier TSV (tab-separated). pandas peut le lire avec pd.read_csv('spam.tsv', sep='\\t', header=None, names=['label','text'])." },
      { step: 1, title: "Explorer les classes", hint: "value_counts() sur la colonne label te donne la distribution spam/ham. Calcule aussi la longueur moyenne des messages avec df['text'].str.len(). Est-ce que les spams sont plus longs ? Cette exploration s'appelle l'Analyse Exploratoire des Données (EDA)." },
      { step: 2, title: "Nettoyer le texte", hint: "Python str a des méthodes utiles : .lower() pour minuscules, .replace() ou re.sub() pour supprimer la ponctuation. Le module re (expressions régulières) est très pratique ici. Commence simple : juste .lower() et applique-le avec df['text'].str.lower()." },
      { step: 3, title: "TF-IDF vs CountVectorizer", hint: "CountVectorizer compte les occurrences de chaque mot. TfidfVectorizer pondère les mots rares (plus informatifs). Les deux sont dans sklearn.feature_extraction.text. Essaie d'abord CountVectorizer — c'est plus simple à comprendre avant TF-IDF." },
      { step: 4, title: "Pourquoi Naive Bayes pour le texte ?", hint: "MultinomialNB est particulièrement efficace pour la classification de texte avec des comptes de mots. Il suppose que les features sont indépendantes (d'où 'naïf'), ce qui est faux en pratique mais donne de très bons résultats sur le texte. Cherche sklearn.naive_bayes.MultinomialNB." },
      { step: 5, title: "Tester avec tes propres messages", hint: "Pour prédire sur un nouveau message, tu dois lui appliquer la même transformation que l'entraînement : vectorizer.transform(['Ton message ici']). Le modèle retourne 0 (ham) ou 1 (spam). Essaie d'écrire un vrai spam et un vrai email normal pour voir si ça marche !" },
    ],
    resources: [
      { label: "SMS Spam Collection dataset", url: "https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset" },
      { label: "sklearn text feature extraction", url: "https://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction" },
    ],
    ai_guidance: "Demande au tuteur d'expliquer ce qu'est TF-IDF, pourquoi Naive Bayes fonctionne bien sur le texte, ou comment interpréter ton F1-score. Pas de code complet.",
  },

  {
    track: "ml",
    id: "p-deb-4",
    title: "Visualisation de données COVID-19",
    level: "debutant",
    hint_level: "high",
    duration: "1 semaine",
    icon: "📈",
    skills: ["Python", "pandas", "matplotlib", "seaborn", "données réelles"],
    description: "Télécharge les données publiques COVID-19 et crée un tableau de bord de visualisations : évolution des cas, comparaison entre pays, courbes de tendance.",
    learning_goal: "Maîtriser les visualisations avec des données réelles imparfaites (valeurs manquantes, formats variés).",
    steps: [
      "Télécharge les données Our World in Data COVID-19",
      "Nettoie les données : gère les valeurs manquantes, convertis les dates",
      "Trace l'évolution des cas pour un pays de ton choix",
      "Compare 3 pays sur le même graphique",
      "Ajoute une moyenne mobile 7 jours pour lisser la courbe",
      "Crée un bar chart des pays les plus touchés (optionnel)",
    ],
    hints: [
      { step: 0, title: "Télécharger les données", hint: "Our World in Data publie un CSV mis à jour : github.com/owid/covid-19-data. Le fichier owid-covid-data.csv contient toutes les colonnes. Télécharge-le et ouvre-le avec pandas pour voir sa structure avec df.columns." },
      { step: 1, title: "Gérer les valeurs manquantes", hint: "df.isnull().sum() te montre combien de valeurs manquent par colonne. Pour les dates, pd.to_datetime() convertit une colonne texte en vrai format date. Pour les NaN dans les cas, .fillna(0) ou .dropna() selon le contexte — pense à ce qui est logique." },
      { step: 2, title: "Filtrer par pays", hint: "La colonne 'location' contient les noms des pays. Filtre avec df[df['location'] == 'Canada']. Ensuite trace plt.plot(df_canada['date'], df_canada['new_cases'])." },
      { step: 3, title: "Plusieurs pays sur un graphique", hint: "Utilise une boucle : for pays in ['Canada', 'France', 'Brazil']: et trace une ligne par pays dans la même figure. plt.legend() ajoute la légende automatiquement si tu passes label= à chaque plt.plot()." },
      { step: 4, title: "Moyenne mobile", hint: "pandas a .rolling(7).mean() qui calcule la moyenne glissante sur 7 jours. Applique-le sur la colonne new_cases et trace les deux courbes (brute + moyenne) sur le même graphique pour voir la différence." },
      { step: 5, title: "Bar chart des pays", hint: "Filtre sur une date précise, groupe par pays avec .groupby('location')['total_cases'].max(), trie avec .sort_values(ascending=False) et prends les 10 premiers avec .head(10). Trace avec plt.barh() pour un bar chart horizontal lisible." },
    ],
    resources: [
      { label: "Our World in Data COVID-19", url: "https://github.com/owid/covid-19-data/tree/master/public/data" },
      { label: "seaborn gallery", url: "https://seaborn.pydata.org/examples/index.html" },
    ],
    ai_guidance: "Le tuteur peut t'aider à comprendre ce qu'est une moyenne mobile, pourquoi on filtre les NaN, ou comment fonctionnent les subplots. Dis-lui exactement où tu bloques.",
  },

  {
    track: "ml",
    id: "p-deb-5",
    title: "Segmenteur d'iris — ton premier clustering",
    level: "debutant",
    hint_level: "high",
    duration: "1 semaine",
    icon: "🌸",
    skills: ["Python", "scikit-learn", "KMeans", "PCA", "matplotlib"],
    description: "Utilise le célèbre dataset Iris pour découvrir le clustering non-supervisé avec K-Means. Visualise les clusters et comprends la différence entre apprentissage supervisé et non-supervisé.",
    learning_goal: "Introduire le clustering et l'apprentissage non-supervisé. Comprendre PCA pour visualiser en 2D.",
    steps: [
      "Charge le dataset Iris depuis sklearn.datasets",
      "Explore : 4 features, 3 espèces, 150 exemples",
      "Applique KMeans avec k=3 et observe les clusters",
      "Compare les clusters trouvés avec les vraies espèces",
      "Réduis en 2D avec PCA et visualise les clusters colorés",
      "Essaie k=2 et k=4 — qu'est-ce qui change ?",
    ],
    hints: [
      { step: 0, title: "Charger Iris", hint: "from sklearn.datasets import load_iris, puis data = load_iris(). C'est un objet avec data.data (les features) et data.target (les espèces). Crée un DataFrame pandas pour mieux explorer : pd.DataFrame(data.data, columns=data.feature_names)." },
      { step: 1, title: "Explorer les features", hint: "Utilise seaborn.pairplot(df, hue='species') pour voir toutes les paires de features en même temps. C'est un outil puissant pour visualiser des données multi-dimensionnelles. C'est l'une des premières choses qu'un Data Scientist fait sur un nouveau dataset." },
      { step: 2, title: "Appliquer KMeans", hint: "from sklearn.cluster import KMeans. kmeans = KMeans(n_clusters=3, random_state=42). kmeans.fit(X). Les labels assignés sont dans kmeans.labels_. IMPORTANT : KMeans ne connaît pas les vraies espèces — il groupe juste par similarité." },
      { step: 3, title: "Comparer avec les vraies espèces", hint: "Les labels KMeans (0, 1, 2) ne correspondent pas forcément aux espèces (0, 1, 2) dans le même ordre. Crée un tableau croisé avec pd.crosstab(kmeans.labels_, data.target) pour voir comment les clusters se superposent aux espèces." },
      { step: 4, title: "Réduire avec PCA", hint: "from sklearn.decomposition import PCA. pca = PCA(n_components=2). X_2d = pca.fit_transform(X). Maintenant tu peux tracer plt.scatter(X_2d[:,0], X_2d[:,1], c=kmeans.labels_). PCA projette les 4 dimensions en 2 en gardant le maximum d'information." },
      { step: 5, title: "Choisir le bon k", hint: "Cherche 'Elbow method KMeans' — c'est une technique pour choisir le bon nombre de clusters. On trace l'inertie (kmeans.inertia_) pour différentes valeurs de k et on cherche le 'coude' de la courbe. Essaie de l'implémenter pour k de 1 à 8." },
    ],
    resources: [
      { label: "sklearn clustering guide", url: "https://scikit-learn.org/stable/modules/clustering.html" },
      { label: "sklearn PCA", url: "https://scikit-learn.org/stable/modules/decomposition.html#pca" },
    ],
    ai_guidance: "Le tuteur peut t'expliquer pourquoi PCA conserve l'information, ce qu'est l'inertie KMeans, ou la différence supervisé/non-supervisé. Pas de solution directe.",
  },

  {
    track: "ml",
    id: "p-deb-6",
    title: "Script CLI d'analyse de fichier texte",
    level: "debutant",
    hint_level: "high",
    duration: "3-4 jours",
    icon: "🖥️",
    skills: ["Python", "argparse", "collections", "fichiers", "CLI"],
    description: "Crée un outil en ligne de commande qui analyse n'importe quel fichier texte : nombre de mots, mots les plus fréquents, longueur moyenne des phrases.",
    learning_goal: "Apprendre à créer de vrais outils Python réutilisables avec argparse, manipulation de fichiers et collections.",
    steps: [
      "Crée un script qui lit un fichier .txt passé en argument",
      "Compte les mots, lignes et caractères",
      "Affiche les 10 mots les plus fréquents (hors mots vides)",
      "Calcule la longueur moyenne des phrases",
      "Ajoute des options CLI : --top N, --output fichier",
      "Gère les erreurs proprement (fichier manquant, encodage)",
    ],
    hints: [
      { step: 0, title: "Lire un argument de ligne de commande", hint: "Python a deux façons : sys.argv (basique) ou argparse (recommandé). import argparse, puis parser = argparse.ArgumentParser(), parser.add_argument('fichier'), args = parser.parse_args(). args.fichier contient le nom du fichier. Lance avec : python analyse.py mon_texte.txt" },
      { step: 1, title: "Compter mots et lignes", hint: "Lis le fichier avec open(args.fichier, 'r', encoding='utf-8') as f: content = f.read(). Puis .split() pour les mots, .split('\\n') pour les lignes, len() pour compter. Simple mais efficace." },
      { step: 2, title: "Mots les plus fréquents", hint: "collections.Counter est parfait pour ça : from collections import Counter. counter = Counter(mots). counter.most_common(10) donne les 10 plus fréquents. Pour les mots vides (le, la, de, et...), crée une liste STOP_WORDS et filtre : [m for m in mots if m not in STOP_WORDS]." },
      { step: 3, title: "Longueur moyenne des phrases", hint: "Sépare le texte en phrases avec re.split(r'[.!?]', text). Enlève les phrases vides avec [s for s in phrases if s.strip()]. Puis calcule la moyenne des len(s.split()) pour chaque phrase." },
      { step: 4, title: "Options CLI avancées", hint: "parser.add_argument('--top', type=int, default=10) ajoute une option optionnelle. parser.add_argument('--output', type=str) pour le fichier de sortie. argparse gère automatiquement l'aide avec python analyse.py --help." },
      { step: 5, title: "Gérer les erreurs", hint: "Entoure ton code d'un try/except. FileNotFoundError si le fichier n'existe pas, UnicodeDecodeError si l'encodage est mauvais. Affiche un message d'erreur clair avec sys.exit(1) pour indiquer l'échec. Un bon outil CLI ne plante jamais silencieusement." },
    ],
    resources: [
      { label: "argparse tutorial Python", url: "https://docs.python.org/3/howto/argparse.html" },
      { label: "collections.Counter", url: "https://docs.python.org/3/library/collections.html#collections.Counter" },
    ],
    ai_guidance: "Ce projet développe de vraies compétences d'ingénierie. Le tuteur peut t'expliquer argparse, les expressions régulières ou la gestion d'erreurs — mais c'est toi qui codes.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ML — INTERMÉDIAIRE — 5 projets
  // ══════════════════════════════════════════════════════════════════════════
  {
    track: "ml",
    id: "p-int-1",
    title: "Prédiction de churn client",
    level: "intermediaire",
    hint_level: "medium",
    duration: "2 semaines",
    icon: "📉",
    skills: ["Python", "scikit-learn", "XGBoost", "SHAP", "feature engineering"],
    description: "Prédit quels clients vont annuler leur abonnement (churn). Pipeline complet : EDA, feature engineering, modèle XGBoost, interprétabilité avec SHAP, recommandations business.",
    learning_goal: "Mener un projet ML de bout en bout avec un dataset réel déséquilibré et présenter des insights actionnables.",
    steps: [
      "EDA sur le Telco Customer Churn dataset — distribution, corrélations, churn rate",
      "Feature engineering : tenure groups, charges par mois, contrat en numérique",
      "Pipeline sklearn : imputation → encoding → scaling → XGBoost",
      "Gérer le déséquilibre des classes (SMOTE ou class_weight)",
      "Évaluer avec AUC-ROC, précision-rappel, matrice de confusion",
      "Expliquer le modèle avec SHAP — quels features causent le churn ?",
      "Rédige 3 recommandations business basées sur les SHAP values",
    ],
    hints: [
      { step: 0, title: "Dataset et EDA", hint: "Dataset Telco sur Kaggle. Pour l'EDA : taux de churn global, distributions par type de contrat, par tenure. Cherche les patterns visuels avant de modéliser." },
      { step: 3, title: "Classes déséquilibrées", hint: "Si seulement 15% de churn, un modèle 'toujours non-churn' a 85% accuracy mais est inutile. Cherche class_weight='balanced' dans XGBClassifier ou explore SMOTE (imblearn library)." },
      { step: 5, title: "SHAP pour l'interprétabilité", hint: "pip install shap. shap.TreeExplainer(model) puis shap.summary_plot(). Chaque feature a une valeur SHAP qui indique son impact sur la prédiction. Lis la doc shap.readthedocs.io pour comprendre les graphiques." },
    ],
    resources: [
      { label: "Telco Churn Kaggle", url: "https://www.kaggle.com/datasets/blastchar/telco-customer-churn" },
      { label: "SHAP documentation", url: "https://shap.readthedocs.io/" },
      { label: "imbalanced-learn", url: "https://imbalanced-learn.org/stable/" },
    ],
    ai_guidance: "Ce niveau demande plus d'autonomie. Le tuteur peut t'orienter vers les bonnes ressources ou t'expliquer un concept, mais tu dois chercher et coder toi-même.",
  },

  {
    track: "ml",
    id: "p-int-2",
    title: "Système de recommandation de films",
    level: "intermediaire",
    hint_level: "medium",
    duration: "2 semaines",
    icon: "🎬",
    skills: ["Python", "pandas", "surprise", "filtrage collaboratif", "similarité cosinus"],
    description: "Construis un moteur de recommandation basé sur les notes utilisateurs (collaborative filtering) et sur le contenu (content-based). Compare les deux approches.",
    learning_goal: "Comprendre les algorithmes de recommandation — la base de Netflix, Spotify, YouTube.",
    steps: [
      "Télécharge le MovieLens 100K dataset",
      "Implémente un filtrage basé sur le contenu (TF-IDF sur les genres/titres)",
      "Implémente un filtrage collaboratif user-user avec la similarité cosinus",
      "Utilise la librairie Surprise pour SVD (matrix factorization)",
      "Évalue avec RMSE sur un split train/test",
      "Compare les 3 approches sur un utilisateur test",
    ],
    hints: [
      { step: 1, title: "Content-based filtering", hint: "Calcule la similarité cosinus entre films à partir de leurs features (genres, tags). sklearn a cosine_similarity() dans sklearn.metrics.pairwise. Pour un film donné, retourne les N films les plus similaires." },
      { step: 2, title: "Collaborative filtering", hint: "Construis une matrice user×film avec les notes. La similarité cosinus entre deux utilisateurs mesure à quel point ils ont les mêmes goûts. Pour prédire la note d'un utilisateur, fais une moyenne pondérée des notes des utilisateurs similaires." },
      { step: 3, title: "Librairie Surprise", hint: "pip install scikit-surprise. from surprise import SVD, Dataset, Reader. SVD est l'algorithme derrière Netflix Prize. Lis le quickstart : surpriselib.com" },
    ],
    resources: [
      { label: "MovieLens dataset", url: "https://grouplens.org/datasets/movielens/100k/" },
      { label: "Surprise library", url: "https://surpriselib.com/" },
    ],
    ai_guidance: "Cherche d'abord à comprendre la similarité cosinus mathématiquement avant de coder. Le tuteur peut t'aider sur les concepts, pas sur le code.",
  },

  {
    track: "ml",
    id: "p-int-3",
    title: "API de détection de sentiments",
    level: "intermediaire",
    hint_level: "medium",
    duration: "2 semaines",
    icon: "💬",
    skills: ["Python", "HuggingFace Transformers", "FastAPI", "Docker"],
    description: "Fine-tune un modèle BERT pour l'analyse de sentiment sur des avis de produits, puis déploie-le comme API REST avec FastAPI et Dockerise le tout.",
    learning_goal: "Utiliser les Transformers pré-entraînés, créer une API ML et la containeriser — compétences directement employables.",
    steps: [
      "Télécharge le dataset Amazon Reviews et explore-le",
      "Fine-tune DistilBERT sur les avis (positif/négatif/neutre) avec HuggingFace Trainer",
      "Évalue : accuracy, F1 par classe, exemples d'erreurs",
      "Crée une API FastAPI avec endpoint POST /predict",
      "Dockerise l'API (Dockerfile + docker-compose)",
      "Teste l'API avec Postman ou curl avec tes propres avis",
    ],
    hints: [
      { step: 1, title: "Fine-tuning DistilBERT", hint: "HuggingFace a un tutorial officiel sur le fine-tuning : huggingface.co/docs/transformers/training. Commence par le Colab fourni avant de faire tourner en local. DistilBERT est 40% plus rapide que BERT pour des performances similaires." },
      { step: 3, title: "FastAPI endpoint ML", hint: "Charge ton modèle une seule fois au démarrage, pas à chaque requête. Utilise une variable globale ou la fonctionnalité lifespan de FastAPI. Un endpoint simple : @app.post('/predict') async def predict(text: str): ... return {'sentiment': label, 'confidence': score}." },
    ],
    resources: [
      { label: "HuggingFace fine-tuning guide", url: "https://huggingface.co/docs/transformers/training" },
      { label: "FastAPI", url: "https://fastapi.tiangolo.com/" },
    ],
    ai_guidance: "Ce projet combine plusieurs technologies. Maîtrise chaque brique séparément avant de tout assembler. Le tuteur peut t'expliquer les concepts mais pas coder pour toi.",
  },

  {
    track: "ml",
    id: "p-int-4",
    title: "Dashboard ML interactif avec Streamlit",
    level: "intermediaire",
    hint_level: "medium",
    duration: "1-2 semaines",
    icon: "📊",
    skills: ["Python", "Streamlit", "plotly", "sklearn"],
    description: "Crée une application web interactive avec Streamlit qui permet d'explorer un dataset, d'entraîner différents modèles ML et de comparer leurs performances en temps réel.",
    learning_goal: "Créer des interfaces pour tes modèles ML — compétence essentielle pour montrer ton travail.",
    steps: [
      "Installe Streamlit et crée une app de base",
      "Ajoute un file uploader pour charger n'importe quel CSV",
      "Affiche des statistiques et visualisations interactives avec Plotly",
      "Laisse l'utilisateur choisir les features et le modèle (RF, LR, XGB)",
      "Entraîne et affiche les métriques en temps réel",
      "Ajoute un onglet comparaison et un export CSV des résultats",
    ],
    hints: [
      { step: 0, title: "Démarrer Streamlit", hint: "pip install streamlit. Crée app.py avec import streamlit as st. Lance avec streamlit run app.py. st.title(), st.write(), st.dataframe() sont tes premiers outils. La doc streamlit.io/docs est excellente." },
      { step: 3, title: "Widgets Streamlit", hint: "st.selectbox() pour choisir un modèle, st.multiselect() pour les features, st.slider() pour les hyperparamètres. Chaque interaction re-run tout le script — c'est la magie de Streamlit." },
    ],
    resources: [
      { label: "Streamlit documentation", url: "https://docs.streamlit.io/" },
      { label: "Plotly Python", url: "https://plotly.com/python/" },
    ],
    ai_guidance: "Streamlit a une excellente doc avec des exemples. Construis chaque section indépendamment avant d'assembler. Le tuteur peut t'aider sur l'architecture de l'app.",
  },

  {
    track: "ml",
    id: "p-int-5",
    title: "Détection d'anomalies dans des séries temporelles",
    level: "intermediaire",
    hint_level: "medium",
    duration: "2 semaines",
    icon: "⚠️",
    skills: ["Python", "pandas", "statsmodels", "Isolation Forest", "séries temporelles"],
    description: "Détecte automatiquement les anomalies dans des données de séries temporelles (transactions financières, métriques serveur ou données IoT). Compare plusieurs approches.",
    learning_goal: "Maîtriser l'analyse de séries temporelles et les algorithmes de détection d'anomalies.",
    steps: [
      "Télécharge un dataset de séries temporelles (trafic réseau, NYSE, ou CPU metrics)",
      "Visualise et comprends la structure temporelle (tendance, saisonnalité)",
      "Implémente une méthode statistique simple (z-score ou IQR)",
      "Applique Isolation Forest pour la détection non-supervisée",
      "Compare les deux méthodes sur les mêmes données",
      "Visualise les anomalies détectées sur la série originale",
    ],
    hints: [
      { step: 1, title: "Décomposition temporelle", hint: "statsmodels.tsa.seasonal.seasonal_decompose() sépare une série en tendance + saisonnalité + résidu. Le résidu est ce qui reste après avoir enlevé les patterns réguliers — c'est là qu'on cherche les anomalies." },
      { step: 3, title: "Isolation Forest", hint: "L'idée : les anomalies sont plus faciles à isoler (moins de splits nécessaires dans un arbre). from sklearn.ensemble import IsolationForest. contamination= fixe le % attendu d'anomalies. Lis la documentation sklearn pour comprendre les paramètres." },
    ],
    resources: [
      { label: "sklearn IsolationForest", url: "https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html" },
      { label: "statsmodels time series", url: "https://www.statsmodels.org/stable/tsa.html" },
    ],
    ai_guidance: "Commence par comprendre les séries temporelles avant de coder. Lis sur la décomposition STL. Le tuteur peut t'expliquer les concepts théoriques.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ML — AVANCÉ — 4 projets
  // ══════════════════════════════════════════════════════════════════════════
  {
    track: "ml",
    id: "p-adv-1",
    title: "RAG Chatbot sur tes propres documents",
    level: "avance",
    hint_level: "none",
    duration: "3-4 semaines",
    icon: "🤖",
    skills: ["Python", "LangChain", "ChromaDB", "HuggingFace Embeddings", "FastAPI", "Docker"],
    description: "Construis un système RAG (Retrieval-Augmented Generation) complet : ingestion de PDF/docs, embeddings vectoriels, retrieval sémantique, génération de réponses avec un LLM. Déploie en API REST.",
    learning_goal: "Maîtriser l'architecture RAG de bout en bout — la technologie derrière la majorité des chatbots d'entreprise.",
    steps: [
      "Ingestion : parse PDF/Word avec PyMuPDF, chunking stratégique",
      "Embeddings : génère des vecteurs avec sentence-transformers",
      "Vector store : stocke dans ChromaDB, implémente la recherche sémantique",
      "Generation : connecte à un LLM (Anthropic/OpenAI) avec prompt engineering",
      "API FastAPI : endpoint /query avec contexte et sources",
      "Évalue la qualité RAG : faithfulness, context relevance, answer relevance",
      "Dockerise et déploie sur un VPS ou AWS EC2",
    ],
    hints: [],
    resources: [
      { label: "LangChain docs", url: "https://docs.langchain.com/" },
      { label: "ChromaDB", url: "https://docs.trychroma.com/" },
      { label: "RAGAS — RAG evaluation", url: "https://docs.ragas.io/" },
    ],
    ai_guidance: "Niveau avancé : le tuteur ne donne pas d'astuces sur ce projet. Si tu bloques : décompose le problème en sous-problèmes, lis la doc officielle, cherche des exemples GitHub. C'est exactement ce qu'un ingénieur ML fait au travail.",
  },

  {
    track: "ml",
    id: "p-adv-2",
    title: "Pipeline MLOps de bout en bout",
    level: "avance",
    hint_level: "none",
    duration: "4 semaines",
    icon: "⚙️",
    skills: ["Python", "MLflow", "DVC", "FastAPI", "Docker", "GitHub Actions", "AWS", "Evidently AI"],
    description: "Construis un pipeline ML production-ready complet : versioning données/modèles, experiment tracking, API de serving, CI/CD automatique, monitoring du drift.",
    learning_goal: "Démontrer une maîtrise complète du cycle de vie ML en production — exactement ce qu'un ML Engineer fait au quotidien.",
    steps: [
      "Choisis un problème métier réel (churn, fraude, prédiction stock)",
      "DVC pour versionner les données + pipeline de feature engineering reproductible",
      "MLflow pour tracker toutes les expériences + model registry",
      "FastAPI pour servir le meilleur modèle sélectionné automatiquement",
      "GitHub Actions : CI (tests, lint) + CD (déploiement auto sur AWS EC2)",
      "Evidently AI : rapport de drift hebdomadaire automatique",
      "Documentation complète : README, architecture diagram, runbook",
    ],
    hints: [],
    resources: [
      { label: "MLflow", url: "https://mlflow.org/" },
      { label: "DVC", url: "https://dvc.org/" },
      { label: "Evidently AI", url: "https://www.evidentlyai.com/" },
      { label: "GitHub Actions", url: "https://docs.github.com/en/actions" },
    ],
    ai_guidance: "C'est ton projet de capstone. Aucune aide directe — tu dois assembler toutes les pièces apprises dans le parcours. Si tu bloques sur un concept spécifique (pas 'fais-le pour moi'), le tuteur peut expliquer.",
  },

  {
    track: "ml",
    id: "p-adv-3",
    title: "Agent AI autonome avec mémoire et outils",
    level: "avance",
    hint_level: "none",
    duration: "3-4 semaines",
    icon: "🧠",
    skills: ["Python", "LangChain Agents", "LLM API", "tools", "mémoire vectorielle", "FastAPI"],
    description: "Construis un agent AI capable d'utiliser des outils (recherche web, calculatrice, base de données, API externes), de mémoriser les conversations et de planifier des tâches multi-étapes.",
    learning_goal: "Comprendre et implémenter les architectures d'agents LLM : ReAct, Chain-of-Thought, tool use, mémoire persistante.",
    steps: [
      "Définis 3-5 outils personnalisés (web search, Python REPL, API météo, base de données)",
      "Implémente l'architecture ReAct (Reasoning + Acting) avec LangChain ou from scratch",
      "Ajoute la mémoire court-terme (conversation) et long-terme (vector store)",
      "Teste sur des tâches complexes multi-étapes (planification, recherche + synthèse)",
      "Gère les erreurs d'outils et les hallucinations (validation des outputs)",
      "Interface web simple avec Streamlit ou FastAPI + HTML",
    ],
    hints: [],
    resources: [
      { label: "LangChain Agents", url: "https://docs.langchain.com/docs/components/agents/" },
      { label: "ReAct paper", url: "https://arxiv.org/abs/2210.03629" },
      { label: "Anthropic Tool Use", url: "https://docs.anthropic.com/en/docs/build-with-claude/tool-use" },
    ],
    ai_guidance: "Ce projet est à la frontière de la recherche et de l'ingénierie. Lis le paper ReAct avant de commencer. L'implémentation from scratch avant d'utiliser LangChain te donnera une vraie compréhension.",
  },

  {
    track: "ml",
    id: "p-adv-4",
    title: "Modèle de Computer Vision pour cas réel",
    level: "avance",
    hint_level: "none",
    duration: "4 semaines",
    icon: "👁️",
    skills: ["Python", "PyTorch", "torchvision", "transfer learning", "YOLO", "OpenCV", "déploiement"],
    description: "Choisis un problème de vision réel (détection de défauts industriels, classification de plantes, comptage d'objets, OCR) et construis un système complet : dataset, training, optimisation, déploiement.",
    learning_goal: "Mener un projet Computer Vision de la collecte de données au déploiement — du dataset au produit utilisable.",
    steps: [
      "Définis le problème et collecte/annote ton dataset (Roboflow, LabelImg)",
      "Choisis l'architecture : classification (ResNet), détection (YOLOv8), segmentation (SAM)",
      "Data augmentation : transforms PyTorch ou Albumentations",
      "Transfer learning depuis un backbone pré-entraîné sur ImageNet",
      "Optimise : quantification, pruning ou ONNX export pour l'inférence rapide",
      "Déploie : API FastAPI + interface web ou app mobile (TFLite/CoreML)",
      "Mesure les performances en conditions réelles et itère",
    ],
    hints: [],
    resources: [
      { label: "PyTorch Vision Tutorial", url: "https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html" },
      { label: "YOLOv8 Ultralytics", url: "https://docs.ultralytics.com/" },
      { label: "Roboflow — annotation", url: "https://roboflow.com/" },
    ],
    ai_guidance: "Ce projet te prépare à un rôle CV Engineer. Commence par un dataset public (Roboflow Universe) avant de collecter le tien. Le tuteur peut discuter architecture et trade-offs, pas coder.",
  },
  // ══════════════════════════════════════════════════════════════════════════
  // WEB FULL STACK — DÉBUTANT — 4 projets
  // ══════════════════════════════════════════════════════════════════════════
  {
    track: "web",
    id: "w-deb-1",
    title: "Portfolio personnel HTML/CSS",
    level: "debutant",
    hint_level: "high",
    duration: "1 semaine",
    icon: "🎨",
    skills: ["HTML5", "CSS3", "Flexbox", "Grid", "responsive design"],
    description: "Construis ton portfolio personnel de A à Z en HTML/CSS pur. Sections : présentation, compétences, projets, contact. Doit être responsive mobile.",
    learning_goal: "Maîtriser les bases HTML/CSS, Flexbox et Grid pour construire une vraie page web sans framework.",
    steps: [
      "Structure HTML sémantique : header, nav, main, sections, footer",
      "Style global : variables CSS (couleurs, typographie), reset, box-model",
      "Section hero : nom, titre, photo, bouton CTA — centré avec Flexbox",
      "Section projets : grille de cartes responsive avec CSS Grid",
      "Section contact : formulaire HTML valide (name, email, message)",
      "Responsive : media queries pour mobile (<768px) et tablette",
      "Déploie sur GitHub Pages gratuitement",
    ],
    hints: [
      { step: 0, title: "Structure sémantique", hint: "HTML5 a des balises de sens : <header>, <nav>, <main>, <section>, <article>, <footer>. Utilise-les — c'est bon pour l'accessibilité et le SEO. Chaque section aura un id= pour la navigation (#projets, #contact)." },
      { step: 1, title: "Variables CSS", hint: ":root { --couleur-principale: #6366f1; --couleur-texte: #1e293b; } Déclare tes couleurs comme variables au niveau :root et utilise var(--couleur-principale) partout. Changer une couleur devient trivial." },
      { step: 2, title: "Centrer avec Flexbox", hint: "Pour centrer verticalement ET horizontalement : display: flex; justify-content: center; align-items: center; sur le conteneur parent. C'est la technique la plus utilisée en CSS moderne." },
      { step: 3, title: "CSS Grid pour les cartes", hint: "display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; — cette ligne crée une grille qui s'adapte automatiquement au nombre de colonnes selon l'espace disponible. Parfait pour des cartes." },
      { step: 5, title: "Media queries", hint: "@media (max-width: 768px) { ... } à placer en fin de fichier. Sur mobile : une seule colonne, nav hamburger ou liens empilés, textes plus petits. Ouvre Chrome DevTools (F12) → icône mobile pour tester." },
      { step: 6, title: "GitHub Pages", hint: "Crée un repo GitHub nommé exactement ton-username.github.io. Push tes fichiers. Ton site sera automatiquement accessible à https://ton-username.github.io. Aucune configuration nécessaire." },
    ],
    resources: [
      { label: "MDN — Learn HTML", url: "https://developer.mozilla.org/fr/docs/Learn/HTML" },
      { label: "CSS Tricks — Flexbox Guide", url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox/" },
      { label: "CSS Tricks — Grid Guide", url: "https://css-tricks.com/snippets/css/complete-guide-grid/" },
      { label: "GitHub Pages", url: "https://pages.github.com/" },
    ],
    ai_guidance: "Le tuteur peut expliquer Flexbox vs Grid, la cascade CSS, ou le box-model — pas écrire ton HTML/CSS à ta place.",
  },

  {
    track: "web",
    id: "w-deb-2",
    title: "Todo App — JavaScript Vanilla",
    level: "debutant",
    hint_level: "high",
    duration: "1 semaine",
    icon: "✅",
    skills: ["JavaScript", "DOM manipulation", "localStorage", "événements"],
    description: "Construis une application de gestion de tâches en JavaScript pur : ajouter, compléter, supprimer, filtrer les tâches. Les données persistent dans localStorage.",
    learning_goal: "Maîtriser la manipulation du DOM, les événements JS et la persistance locale — les fondations du JavaScript côté client.",
    steps: [
      "Structure HTML : input + bouton ajout, liste de tâches, filtres (Tout/Actif/Complété)",
      "JavaScript : écouter le submit du formulaire, créer l'élément li dynamiquement",
      "Compléter une tâche : toggle classe 'completed' au clic, style barré en CSS",
      "Supprimer une tâche : bouton × par tâche, removeChild",
      "Filtres : afficher/masquer les tâches selon leur état",
      "localStorage : sauvegarder le tableau de tâches en JSON, recharger au démarrage",
    ],
    hints: [
      { step: 0, title: "Structure HTML de base", hint: "<form id='todo-form'><input id='todo-input' type='text' placeholder='Nouvelle tâche'><button type='submit'>Ajouter</button></form><ul id='todo-list'></ul>. Les filtres : 3 boutons avec data-filter='all', 'active', 'completed'." },
      { step: 1, title: "Écouter un événement", hint: "document.getElementById('todo-form').addEventListener('submit', function(e) { e.preventDefault(); const texte = document.getElementById('todo-input').value.trim(); if (!texte) return; /* créer la tâche */ });" },
      { step: 2, title: "Créer un élément dynamiquement", hint: "const li = document.createElement('li'); li.textContent = texte; li.classList.add('todo-item'); document.getElementById('todo-list').appendChild(li); li.addEventListener('click', () => li.classList.toggle('completed'));" },
      { step: 4, title: "Logique de filtrage", hint: "Garde un tableau tasks = [] avec { text, completed }. Au lieu de cacher des éléments DOM, re-rends toute la liste à partir du tableau filtré. C'est le principe de base de React — une source de vérité unique." },
      { step: 5, title: "localStorage", hint: "localStorage.setItem('tasks', JSON.stringify(tasks)) pour sauvegarder. JSON.parse(localStorage.getItem('tasks') || '[]') pour relire au chargement. Appelle la sauvegarde à chaque modification." },
    ],
    resources: [
      { label: "MDN — DOM Manipulation", url: "https://developer.mozilla.org/fr/docs/Web/API/Document_Object_Model/Introduction" },
      { label: "MDN — localStorage", url: "https://developer.mozilla.org/fr/docs/Web/API/Window/localStorage" },
    ],
    ai_guidance: "Ce projet enseigne la logique fondamentale de tout framework. Le tuteur peut expliquer les closures, le bubbling d'événements ou JSON — pas coder la solution.",
  },

  {
    track: "web",
    id: "w-deb-3",
    title: "App météo avec une API publique",
    level: "debutant",
    hint_level: "high",
    duration: "1 semaine",
    icon: "🌤️",
    skills: ["JavaScript", "fetch API", "JSON", "API REST", "async/await"],
    description: "Crée une app météo qui récupère les données en temps réel via l'API Open-Meteo (gratuite, sans clé). Affiche température, humidité, vent et icône météo selon la ville cherchée.",
    learning_goal: "Apprendre à consommer une API REST avec fetch/async-await et afficher des données JSON dynamiquement.",
    steps: [
      "Interface : barre de recherche ville, bouton, zone d'affichage météo",
      "Géocoding : convertir le nom de ville en coordonnées GPS (API Open-Meteo geocoding)",
      "Météo : requête fetch vers Open-Meteo avec lat/lon, parser le JSON",
      "Affichage : température, ressenti, humidité, vitesse du vent, description",
      "Icône météo : code WMO → emoji ou icône (table de correspondance)",
      "Gestion d'erreurs : ville introuvable, réseau coupé, feedback utilisateur",
    ],
    hints: [
      { step: 1, title: "API Geocoding Open-Meteo", hint: "URL : https://geocoding-api.open-meteo.com/v1/search?name=Paris&count=1&language=fr. Retourne lat/lon dans results[0]. Utilise fetch(url).then(r => r.json()).then(data => ...) ou async/await." },
      { step: 2, title: "Requête météo", hint: "URL : https://api.open-meteo.com/v1/forecast?latitude=48.85&longitude=2.35&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code. Toutes les données sont dans data.current." },
      { step: 3, title: "async/await", hint: "async function getWeather(city) { try { const geo = await fetch(geoUrl).then(r => r.json()); const { latitude, longitude } = geo.results[0]; const weather = await fetch(weatherUrl(latitude, longitude)).then(r => r.json()); afficher(weather.current); } catch(e) { afficherErreur(e.message); } }" },
      { step: 4, title: "Codes WMO → description", hint: "L'API retourne un weather_code (0=ciel dégagé, 1-3=nuages, 45=brouillard, 61-67=pluie, 71-77=neige, 80-82=averses, 95=orage). Crée un objet WMO_CODES = { 0: { desc: 'Ensoleillé', emoji: '☀️' }, 1: ..., } pour la correspondance." },
      { step: 5, title: "Gestion d'erreurs", hint: "Entoure tes fetches de try/catch. Affiche un message visible si ville non trouvée (geo.results?.length === 0) ou si le réseau coupe (catch). Un bon UX montre toujours à l'utilisateur ce qui se passe." },
    ],
    resources: [
      { label: "Open-Meteo (gratuit, sans clé)", url: "https://open-meteo.com/en/docs" },
      { label: "MDN — fetch API", url: "https://developer.mozilla.org/fr/docs/Web/API/Fetch_API/Using_Fetch" },
      { label: "MDN — async/await", url: "https://developer.mozilla.org/fr/docs/Learn/JavaScript/Asynchronous/Promises" },
    ],
    ai_guidance: "Comprends d'abord ce qu'est une promesse JS avant de coder. Le tuteur peut expliquer async/await, JSON.parse, ou la gestion d'erreurs réseau.",
  },

  {
    track: "web",
    id: "w-deb-4",
    title: "Quiz interactif — React débutant",
    level: "debutant",
    hint_level: "high",
    duration: "1 semaine",
    icon: "🧠",
    skills: ["React", "useState", "props", "composants", "JSX"],
    description: "Construis un quiz interactif avec React : questions à choix multiples, timer par question, score final, possibilité de recommencer. Découverte des fondations React.",
    learning_goal: "Comprendre les composants React, useState, les props et le rendu conditionnel — les 4 piliers de React.",
    steps: [
      "Crée l'app avec Vite (npm create vite@latest quiz -- --template react)",
      "Composant Question : affiche la question et 4 boutons de réponses",
      "useState pour tracker : question courante, score, réponse sélectionnée",
      "Logique de réponse : highlight vert/rouge, passer à la question suivante",
      "Composant ScoreFinal : affiche le score, message selon résultat, bouton restart",
      "Timer : countdown de 15s par question avec useEffect + setInterval",
    ],
    hints: [
      { step: 0, title: "Démarrer avec Vite", hint: "npm create vite@latest mon-quiz -- --template react, puis cd mon-quiz && npm install && npm run dev. Supprime le contenu de App.jsx et commence proprement. Vite est bien plus rapide que create-react-app." },
      { step: 1, title: "Données du quiz", hint: "Crée un fichier questions.js avec un tableau : [{ question: '...', options: ['A', 'B', 'C', 'D'], answer: 1 }, ...]. Importe-le dans App.jsx. Garde les données séparées de l'UI." },
      { step: 2, title: "useState de base", hint: "const [currentQ, setCurrentQ] = useState(0); const [score, setScore] = useState(0); const [selected, setSelected] = useState(null); Chaque setState déclenche un re-render — React met à jour l'UI automatiquement." },
      { step: 3, title: "Rendu conditionnel", hint: "Si selected !== null, colorier le bouton sélectionné (rouge si faux, vert si juste) et le bouton de la bonne réponse (toujours vert). Utilise une ternaire dans className: className={selected === i ? (i === answer ? 'correct' : 'wrong') : ''}" },
      { step: 5, title: "useEffect + timer", hint: "useEffect(() => { const timer = setInterval(() => setTime(t => t - 1), 1000); return () => clearInterval(timer); }, [currentQ]); Le return nettoie le timer quand la question change. Quand time === 0, passe à la question suivante." },
    ],
    resources: [
      { label: "React — Learn React (doc officielle)", url: "https://react.dev/learn" },
      { label: "Vite — Getting Started", url: "https://vitejs.dev/guide/" },
    ],
    ai_guidance: "Le tuteur peut expliquer le cycle de vie React, pourquoi les hooks ne peuvent pas être dans des conditions, ou la différence entre state et props.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEB FULL STACK — INTERMÉDIAIRE — 4 projets
  // ══════════════════════════════════════════════════════════════════════════
  {
    track: "web",
    id: "w-int-1",
    title: "Blog full stack avec Next.js + Supabase",
    level: "intermediaire",
    hint_level: "medium",
    duration: "2-3 semaines",
    icon: "📝",
    skills: ["Next.js 14", "Supabase", "TypeScript", "Auth", "Postgres", "Tailwind CSS"],
    description: "Construis un blog complet avec authentification, CRUD des articles (Markdown), commentaires, et panneau d'administration. Stack : Next.js App Router + Supabase + TypeScript.",
    learning_goal: "Maîtriser le full stack moderne : Server Components, Route Handlers, Auth avec Supabase, et Postgres en production.",
    steps: [
      "Setup : Next.js 14 App Router + TypeScript + Tailwind + Supabase client",
      "Schéma Supabase : tables posts (title, content, slug, published) + comments + users",
      "Auth : inscription/connexion email avec Supabase Auth, middleware de protection des routes",
      "Liste des articles : Server Component, fetch Supabase côté serveur, pagination",
      "Éditeur Markdown : page /admin/posts/new avec preview en temps réel",
      "Page article : rendu Markdown, section commentaires (optimistic UI)",
      "Déploiement Vercel : variables d'env, preview deployments",
    ],
    hints: [
      { step: 1, title: "Schéma SQL Supabase", hint: "CREATE TABLE posts (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, title text NOT NULL, slug text UNIQUE NOT NULL, content text, published boolean DEFAULT false, author_id uuid REFERENCES auth.users, created_at timestamptz DEFAULT now()); Active RLS et crée les policies select/insert/update." },
      { step: 2, title: "Middleware Next.js", hint: "middleware.js à la racine : vérifie la session Supabase avec createServerClient. Redirige vers /login si pas de session sur les routes /admin/*. Consulte la doc @supabase/ssr pour l'intégration correcte avec App Router." },
      { step: 5, title: "Optimistic UI commentaires", hint: "Avec useOptimistic() de React 18 : affiche le commentaire immédiatement dans l'UI avant que le serveur confirme. Si ça échoue, rollback. Meilleure UX qu'attendre la réponse serveur." },
    ],
    resources: [
      { label: "Next.js — App Router", url: "https://nextjs.org/docs/app" },
      { label: "Supabase — Next.js Quickstart", url: "https://supabase.com/docs/guides/getting-started/quickstarts/nextjs" },
      { label: "next-mdx-remote", url: "https://github.com/hashicorp/next-mdx-remote" },
    ],
    ai_guidance: "Ce projet combine plusieurs technologies. Construis par couches — d'abord l'auth fonctionne, puis le CRUD, puis les commentaires. Le tuteur peut expliquer les Server vs Client Components.",
  },

  {
    track: "web",
    id: "w-int-2",
    title: "Clone Trello — Drag & Drop avec React",
    level: "intermediaire",
    hint_level: "medium",
    duration: "2 semaines",
    icon: "📋",
    skills: ["React", "TypeScript", "dnd-kit", "Zustand", "CSS avancé"],
    description: "Construis un gestionnaire de tâches style Kanban avec drag & drop entre colonnes, édition en ligne, et persistance locale. Implémente les optimizations de performance React.",
    learning_goal: "Maîtriser le state management complexe, le drag & drop, et les patterns React avancés (memo, useCallback).",
    steps: [
      "Setup : Vite + React + TypeScript + dnd-kit + Zustand",
      "Structure de données TypeScript : Board, Column, Card avec IDs uniques",
      "Rendu des colonnes et cartes avec types stricts",
      "Drag & drop des cartes entre colonnes avec @dnd-kit/sortable",
      "Édition en ligne des cartes (double-clic → input, blur → save)",
      "Ajout/suppression de colonnes et cartes dynamiquement",
      "Optimisations : React.memo sur les cartes, useCallback sur les handlers",
    ],
    hints: [
      { step: 0, title: "Types TypeScript pour le board", hint: "type Card = { id: string; title: string; description?: string }; type Column = { id: string; title: string; cards: Card[] }; type Board = { columns: Column[] }; Commence par bien typer ta structure de données avant de coder l'UI." },
      { step: 3, title: "dnd-kit setup", hint: "npm install @dnd-kit/core @dnd-kit/sortable @dnd-kit/utilities. Entoure l'app de <DndContext onDragEnd={handleDragEnd}>. Chaque colonne devient un <SortableContext items={column.cards.map(c => c.id)}>. Lis le quickstart officiel docs.dndkit.com." },
      { step: 6, title: "Optimisations React", hint: "Sans memo, chaque modification d'une carte re-rend TOUTES les cartes. React.memo(CardComponent) ne re-rend que si les props changent. Combine avec useCallback pour les fonctions passées en props — sinon la référence change à chaque render." },
    ],
    resources: [
      { label: "dnd-kit documentation", url: "https://docs.dndkit.com/" },
      { label: "Zustand — state management", url: "https://zustand-demo.pmnd.rs/" },
    ],
    ai_guidance: "Comprends d'abord le modèle de données avant de toucher au drag & drop. Le tuteur peut expliquer pourquoi React.memo aide et quand ne pas l'utiliser.",
  },

  {
    track: "web",
    id: "w-int-3",
    title: "API REST Express + TypeScript + PostgreSQL",
    level: "intermediaire",
    hint_level: "medium",
    duration: "2 semaines",
    icon: "⚙️",
    skills: ["Node.js", "Express", "TypeScript", "PostgreSQL", "Zod", "JWT", "Docker"],
    description: "Construis une API REST complète pour une app de gestion de bibliothèque : CRUD livres/auteurs, authentification JWT, validation Zod, tests d'intégration avec Jest.",
    learning_goal: "Maîtriser le développement backend Node.js typé : architecture, validation, auth JWT, base de données, tests.",
    steps: [
      "Setup : Express + TypeScript + ts-node-dev, structure en couches (routes/controllers/services/db)",
      "Base de données : PostgreSQL avec pg, migrations SQL, pool de connexions",
      "CRUD livres : GET /books, POST /books, PUT /books/:id, DELETE /books/:id",
      "Validation Zod : schéma pour chaque request body et params",
      "Auth JWT : POST /auth/register et /auth/login, middleware de vérification du token",
      "Tests d'intégration avec Supertest : tester chaque endpoint avec une DB de test",
      "Dockerise l'API + PostgreSQL avec docker-compose",
    ],
    hints: [
      { step: 0, title: "Architecture en couches", hint: "routes/ → définit les URLs. controllers/ → reçoit req/res, appelle les services. services/ → logique métier. db/ → requêtes SQL. Cette séparation rend le code testable et maintenable. Ne mets jamais de SQL dans les controllers." },
      { step: 3, title: "Validation Zod dans Express", hint: "const createBookSchema = z.object({ title: z.string().min(1), author_id: z.number().int() }); const validateBody = (schema) => (req, res, next) => { const result = schema.safeParse(req.body); if (!result.success) return res.status(400).json(result.error); req.body = result.data; next(); };" },
      { step: 4, title: "JWT middleware", hint: "const authMiddleware = (req, res, next) => { const token = req.headers.authorization?.split(' ')[1]; if (!token) return res.status(401).json({ error: 'Non authentifié' }); try { req.user = jwt.verify(token, process.env.JWT_SECRET); next(); } catch { res.status(401).json({ error: 'Token invalide' }); } };" },
    ],
    resources: [
      { label: "Express + TypeScript setup", url: "https://www.digitalocean.com/community/tutorials/setting-up-a-node-project-with-typescript" },
      { label: "Zod documentation", url: "https://zod.dev/" },
      { label: "Supertest — testing HTTP", url: "https://github.com/ladjs/supertest" },
    ],
    ai_guidance: "Ce projet te donne les bases du backend professionnel. Construis les couches une par une. Le tuteur peut expliquer JWT, le pool de connexions ou l'architecture REST.",
  },

  {
    track: "web",
    id: "w-int-4",
    title: "SaaS dashboard — Next.js + Stripe + Auth",
    level: "intermediaire",
    hint_level: "medium",
    duration: "3 semaines",
    icon: "💳",
    skills: ["Next.js 14", "Supabase Auth", "Stripe", "TypeScript", "Tailwind", "Webhooks"],
    description: "Construis un micro-SaaS complet : authentification, plan gratuit vs premium, paiement Stripe, dashboard utilisateur, et webhooks pour synchroniser les abonnements.",
    learning_goal: "Comprendre l'architecture complète d'un SaaS : auth, paiement, webhooks, et gestion des rôles — compétences directement employables.",
    steps: [
      "Auth Supabase : inscription, connexion, profil utilisateur avec rôle (free/premium)",
      "Dashboard protégé : page accessible uniquement aux utilisateurs connectés",
      "Page pricing : plans Free/Pro avec Stripe Checkout Session",
      "Webhook Stripe : écouter checkout.session.completed et customer.subscription.deleted",
      "Mise à jour du rôle en DB après paiement confirmé par webhook",
      "Feature gating : composant <PremiumOnly> qui affiche un paywall si non-premium",
      "Page de gestion abonnement : lien vers Stripe Customer Portal",
    ],
    hints: [
      { step: 2, title: "Stripe Checkout", hint: "Route API POST /api/checkout : const session = await stripe.checkout.sessions.create({ mode: 'subscription', line_items: [{ price: PRICE_ID, quantity: 1 }], success_url, cancel_url, customer_email: user.email }); return redirect(session.url);" },
      { step: 3, title: "Webhook Stripe", hint: "Route POST /api/webhook avec stripe.webhooks.constructEvent(rawBody, sig, WEBHOOK_SECRET). Traite checkout.session.completed pour upgrader l'utilisateur. En dev : utilise stripe listen --forward-to localhost:3000/api/webhook." },
      { step: 5, title: "Feature gating", hint: "Récupère le rôle depuis la DB à chaque requête (middleware ou Server Component). <PremiumOnly> : si user.role !== 'premium', affiche un overlay avec le prix et bouton upgrade. Simple mais efficace pour un MVP." },
    ],
    resources: [
      { label: "Stripe Next.js integration", url: "https://stripe.com/docs/payments/checkout/how-checkout-works" },
      { label: "Stripe Webhooks", url: "https://stripe.com/docs/webhooks" },
      { label: "Stripe CLI", url: "https://stripe.com/docs/stripe-cli" },
    ],
    ai_guidance: "Ce projet simule un vrai SaaS. Le tuteur peut expliquer la sécurité des webhooks (validation de signature), le flow OAuth ou la différence entre Checkout et PaymentIntent.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEB FULL STACK — AVANCÉ — 2 projets
  // ══════════════════════════════════════════════════════════════════════════
  {
    track: "web",
    id: "w-adv-1",
    title: "Réseau social temps réel avec WebSockets",
    level: "avance",
    hint_level: "none",
    duration: "4 semaines",
    icon: "💬",
    skills: ["Next.js", "Socket.io", "Redis", "PostgreSQL", "TypeScript", "React Query", "Vercel"],
    description: "Construis un mini réseau social avec posts, likes, commentaires, notifications en temps réel via WebSockets, feed personnalisé, et upload d'images sur Supabase Storage.",
    learning_goal: "Maîtriser l'architecture temps réel, la gestion de l'état serveur complexe et les optimisations de performance web.",
    steps: [
      "Architecture : Next.js frontend + Node.js/Express WebSocket server + PostgreSQL + Redis",
      "Auth & profils : Supabase Auth, avatar upload sur Storage, bio, followers/following",
      "Posts & feed : pagination infinie, algorithme de feed (chronologique + affinité)",
      "Likes & commentaires : optimistic updates avec React Query, count en temps réel",
      "Notifications temps réel : Socket.io, Redis pub/sub pour scalabilité",
      "Upload images : Supabase Storage, resize côté serveur avec Sharp, CDN",
      "Performance : indexation PostgreSQL, cache Redis, lazy loading images",
    ],
    hints: [],
    resources: [
      { label: "Socket.io documentation", url: "https://socket.io/docs/v4/" },
      { label: "Redis — pub/sub", url: "https://redis.io/docs/manual/pubsub/" },
      { label: "React Query", url: "https://tanstack.com/query/latest" },
    ],
    ai_guidance: "Niveau avancé : commence par un schéma de données solide avant de coder. Pense à la scalabilité dès le début — Redis est là pour une raison. Le tuteur discute architecture, pas code.",
  },

  {
    track: "web",
    id: "w-adv-2",
    title: "Compilateur / interpréteur minimaliste",
    level: "avance",
    hint_level: "none",
    duration: "4-6 semaines",
    icon: "⚙️",
    skills: ["TypeScript", "AST", "parsing", "interprétation", "algorithmes", "tests"],
    description: "Implémente un langage de programmation minimaliste : lexer, parser, AST, et interpréteur. Supporte variables, fonctions, boucles, et closures. Avec playground web interactif.",
    learning_goal: "Comprendre en profondeur comment fonctionnent les langages de programmation — le projet le plus formateur en informatique fondamentale.",
    steps: [
      "Lexer : tokenize le code source en tokens (NUMBER, STRING, IDENT, OP, ...)",
      "Parser : transforme les tokens en AST (Abstract Syntax Tree) — recursive descent",
      "Évaluateur : interprète l'AST — expressions, variables, conditions",
      "Fonctions et closures : environnements imbriqués, portée lexicale",
      "Boucles et récursion : while, for, appels récursifs avec stack depth limite",
      "Tests : suite complète avec Jest — chaque feature a ses tests",
      "Playground web : éditeur CodeMirror + résultat en temps réel dans React",
    ],
    hints: [],
    resources: [
      { label: "Crafting Interpreters (livre gratuit)", url: "https://craftinginterpreters.com/" },
      { label: "Writing An Interpreter In Go", url: "https://interpreterbook.com/" },
    ],
    ai_guidance: "Lis Crafting Interpreters avant de commencer — c'est la ressource parfaite. Ce projet est difficile et formateur. Le tuteur peut discuter des concepts théoriques, pas donner d'implémentation.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PMP 2026 — DÉBUTANT — 3 projets
  // ══════════════════════════════════════════════════════════════════════════
  {
    track: "pmp",
    id: "pmp-deb-1",
    title: "Plan de projet complet — événement fictif",
    level: "debutant",
    hint_level: "high",
    duration: "1 semaine",
    icon: "📅",
    skills: ["Charte de projet", "WBS", "Diagramme de Gantt", "registre des risques", "PMBOK"],
    description: "Planifie de A à Z un événement fictif (conférence de 200 personnes, hackathon, formation). Produis tous les livrables de planification : charte, WBS, Gantt, budget, risques.",
    learning_goal: "Maîtriser les livrables fondamentaux de la planification de projet selon le PMBOK 7 et l'ECO 2026.",
    steps: [
      "Rédige la Charte de projet : objectifs, périmètre, parties prenantes clés, budget estimé, jalons",
      "WBS (Work Breakdown Structure) : décompose le projet en livrables et lots de travaux sur 3 niveaux",
      "Diagramme de Gantt : durées, dépendances, chemin critique, jalons (utilise ProjectLibre ou Excel)",
      "Registre des risques : identifie 8 risques, évalue probabilité × impact, définis les réponses",
      "Budget prévisionnel : estimation par lot de travaux, réserve pour aléas (10-15%)",
      "Plan de communication : qui reçoit quoi, à quelle fréquence, par quel canal",
    ],
    hints: [
      { step: 0, title: "Structure d'une charte de projet", hint: "La charte autorise le projet et donne autorité au chef de projet. Sections clés : contexte et justification, objectifs SMART, périmètre (dans/hors périmètre), parties prenantes clés, contraintes (budget, délai), hypothèses, signature du sponsor." },
      { step: 1, title: "Règles du WBS", hint: "Règle des 100% : le WBS doit couvrir 100% du travail. Chaque élément de niveau inférieur doit totaliser 100% de son parent. Niveau 1 = projet, Niveau 2 = phases ou livrables majeurs, Niveau 3 = lots de travaux (work packages). Pas de verbes dans les intitulés — ce sont des livrables, pas des tâches." },
      { step: 2, title: "Chemin critique", hint: "Le chemin critique = la séquence de tâches la plus longue sans marge. Un retard sur le chemin critique = retard du projet. Dans un Gantt, identifie les tâches sans float (marge libre = 0). ProjectLibre le calcule automatiquement." },
      { step: 3, title: "Matrice probabilité × impact", hint: "Score de risque = Probabilité (1-5) × Impact (1-5). Score ≥ 15 = risque majeur (rouge). 8-14 = modéré (orange). < 8 = mineur (vert). Pour chaque risque : Éviter, Transférer, Atténuer, ou Accepter. Documente le déclencheur et le responsable." },
    ],
    resources: [
      { label: "PMBOK Guide 7e édition — résumé", url: "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok" },
      { label: "ProjectLibre (Gantt gratuit)", url: "https://www.projectlibre.com/" },
      { label: "Template WBS Excel — PMI", url: "https://www.projectmanagement.com/templates/index.cfm" },
    ],
    ai_guidance: "Le tuteur peut expliquer la différence entre WBS et Gantt, comment calculer le chemin critique, ou les types de réponses aux risques — pas remplir les templates à ta place.",
  },

  {
    track: "pmp",
    id: "pmp-deb-2",
    title: "Registre des parties prenantes & plan d'engagement",
    level: "debutant",
    hint_level: "high",
    duration: "4-5 jours",
    icon: "👥",
    skills: ["Identification parties prenantes", "grille pouvoir/intérêt", "plan d'engagement", "communication"],
    description: "Pour un projet fictif de transformation digitale d'une PME, identifie toutes les parties prenantes, analyse leur influence et crée un plan d'engagement personnalisé pour chacune.",
    learning_goal: "Maîtriser le processus d'identification et gestion des parties prenantes — l'un des domaines les plus importants du PMP ECO 2026 (People 33%).",
    steps: [
      "Identifie 12 parties prenantes internes et externes du projet",
      "Remplis le registre des parties prenantes : rôle, intérêts, influence, attentes",
      "Grille Pouvoir/Intérêt : place chaque partie prenante dans la matrice 2×2",
      "Grille d'engagement : état actuel vs désiré (Inconscient/Résistant/Neutre/Favorable/Champion)",
      "Plan d'engagement : actions spécifiques pour déplacer chaque partie vers l'état désiré",
      "Plan de communication associé : fréquence, canal, contenu, émetteur pour chacune",
    ],
    hints: [
      { step: 0, title: "Qui sont les parties prenantes ?", hint: "Toute personne ou groupe affecté par le projet ou pouvant l'affecter. Pense large : sponsor, équipe projet, clients, fournisseurs, régulateurs, équipes impactées, syndicats, actionnaires, communauté locale. L'outil PESTEL peut t'aider à identifier les externes." },
      { step: 2, title: "Grille Pouvoir/Intérêt", hint: "4 quadrants : Fort pouvoir + Fort intérêt = Gérer étroitement. Fort pouvoir + Faible intérêt = Satisfaire. Faible pouvoir + Fort intérêt = Tenir informé. Faible pouvoir + Faible intérêt = Surveiller. Chaque quadrant a une stratégie d'engagement différente." },
      { step: 3, title: "Niveaux d'engagement", hint: "Inconscient : ne sait pas que le projet existe. Résistant : sait et s'oppose. Neutre : indifférent. Favorable : soutient. Champion : défend activement le projet. L'état désiré n'est pas toujours 'Champion' — pour certaines parties, 'Neutre' suffit." },
    ],
    resources: [
      { label: "PMI — Stakeholder Engagement", url: "https://www.pmi.org/learning/library/stakeholder-engagement-essentials-8779" },
      { label: "Template registre des parties prenantes", url: "https://www.projectmanagement.com/templates/index.cfm" },
    ],
    ai_guidance: "Ce projet développe une compétence People critique pour le PMP. Le tuteur peut expliquer les stratégies d'engagement ou la différence entre parties prenantes primaires et secondaires.",
  },

  {
    track: "pmp",
    id: "pmp-deb-3",
    title: "Analyse de cas — projet en difficulté",
    level: "debutant",
    hint_level: "high",
    duration: "4-5 jours",
    icon: "🚨",
    skills: ["analyse de situation", "EVM", "gestion de crise", "décision", "PMBOK"],
    description: "Analyse un projet fictif en difficulté (retards, dépassement budget, conflits d'équipe) et produis un plan de redressement complet avec calculs EVM et recommandations.",
    learning_goal: "Apprendre à diagnostiquer un projet défaillant, calculer les indicateurs EVM et prendre des décisions en situation de crise.",
    steps: [
      "Lis le cas : projet de 6 mois à la semaine 14, budget 200k€, indicateurs fournis",
      "Calcule les indicateurs EVM : PV, EV, AC, CV, SV, CPI, SPI",
      "Interprète : le projet est-il en avance/retard ? Sur/sous budget ? De combien ?",
      "Identifie les causes racines des problèmes (analyse des 5 pourquoi ou Fishbone)",
      "Propose 5 actions correctives concrètes avec responsable et délai",
      "Estime EAC (coût final estimé) et projette la date de fin révisée",
    ],
    hints: [
      { step: 1, title: "Formules EVM de base", hint: "PV = Planned Value (budget prévu pour le travail planifié). EV = Earned Value (valeur du travail réellement fait). AC = Actual Cost (coût réel dépensé). CV = EV - AC (positif = sous budget). SV = EV - PV (positif = en avance). CPI = EV/AC. SPI = EV/PV." },
      { step: 2, title: "Interpréter CPI et SPI", hint: "CPI > 1 = efficace (on fait plus que prévu avec l'argent dépensé). CPI < 1 = inefficace. SPI > 1 = en avance. SPI < 1 = en retard. CPI = 0.82 signifie que pour 1€ dépensé, on produit 0.82€ de valeur — on dépense 22% de trop." },
      { step: 5, title: "Calculer EAC", hint: "EAC (Estimate at Completion) = BAC / CPI si la tendance continue. BAC = Budget At Completion (budget total). Si CPI = 0.82 et BAC = 200k€, EAC = 200k/0.82 = 244k€. L'écart (EAC - BAC) est le dépassement prévu." },
    ],
    resources: [
      { label: "PMI — EVM Practice Standard", url: "https://www.pmi.org/pmbok-guide-standards/practice-guides/evm" },
      { label: "EVM Calculator en ligne", url: "https://www.calculatorsoup.com/calculators/financial/earned-value-analysis.php" },
    ],
    ai_guidance: "Le tuteur peut t'aider à comprendre les formules EVM ou interpréter les indicateurs — pas faire les calculs à ta place ni rédiger le plan de redressement.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PMP 2026 — INTERMÉDIAIRE — 3 projets
  // ══════════════════════════════════════════════════════════════════════════
  {
    track: "pmp",
    id: "pmp-int-1",
    title: "Simulation complète — projet agile/hybride",
    level: "intermediaire",
    hint_level: "medium",
    duration: "2 semaines",
    icon: "🔄",
    skills: ["Scrum", "Kanban", "hybride", "user stories", "sprint planning", "backlog", "vélocité"],
    description: "Simule la gestion complète d'un projet hybride (phases prédictives + sprints agiles) sur 3 mois : backlog produit, sprint planning, rétrospectives, et reporting EVM adapté à l'agile.",
    learning_goal: "Maîtriser l'approche hybride prédictive/agile — la réalité de la plupart des entreprises et un pilier de l'ECO PMP 2026.",
    steps: [
      "Cadrage : définit les phases prédictives (architecture, contrats) vs agiles (développement)",
      "Product Backlog : 20 user stories en format 'En tant que... je veux... afin de...' avec story points",
      "Sprint 0 : setup technique, définition du DoD (Definition of Done), vélocité initiale estimée",
      "Simulation Sprint 1-4 : sprint planning, daily standup (notes), review, rétrospective",
      "Reporting hybride : burndown chart + indicateurs EVM adaptés (EV = story points livrés × valeur)",
      "Gestion d'un obstacle : une dépendance externe bloque le Sprint 3 — comment adapter ?",
    ],
    hints: [
      { step: 1, title: "User stories bien formées", hint: "Format : 'En tant que [utilisateur], je veux [fonctionnalité] afin de [bénéfice].' Critères d'acceptation : Given/When/Then. Une user story doit être INVEST : Indépendante, Négociable, Valeur ajoutée, Estimable, Small, Testable." },
      { step: 3, title: "Rétrospective efficace", hint: "Format Start/Stop/Continue : qu'est-ce qu'on devrait commencer à faire ? Arrêter ? Continuer ? Limite à 3 actions max par rétro — trop d'actions = aucune ne sera faite. Le Scrum Master facilite, ne décide pas." },
      { step: 5, title: "Gestion d'un obstacle", hint: "Un blocage externe = risque matérialisé. Options : (1) Réordonnancer — passer aux stories suivantes pendant l'attente. (2) Escalader au sponsor. (3) Accepter le retard et replanifier. Documente l'impact sur la vélocité et le burndown." },
    ],
    resources: [
      { label: "Scrum Guide 2020", url: "https://scrumguides.org/scrum-guide.html" },
      { label: "PMI — Agile Practice Guide", url: "https://www.pmi.org/pmbok-guide-standards/practice-guides/agile" },
    ],
    ai_guidance: "Le tuteur peut expliquer la différence Scrum/Kanban, comment calculer la vélocité ou adapter l'EVM à l'agile — pas remplir les templates à ta place.",
  },

  {
    track: "pmp",
    id: "pmp-int-2",
    title: "Stratégie de risques — projet de construction",
    level: "intermediaire",
    hint_level: "medium",
    duration: "1-2 semaines",
    icon: "⚠️",
    skills: ["identification des risques", "analyse qualitative", "analyse quantitative", "Monte Carlo", "réponses aux risques"],
    description: "Pour un projet de construction d'un entrepôt logistique (budget 2M€, 8 mois), réalise une analyse des risques complète : qualitative, quantitative (simulation Monte Carlo), et plan de réponse.",
    learning_goal: "Maîtriser le processus complet de gestion des risques PMBOK — de l'identification à la réponse, en passant par les analyses qualitative et quantitative.",
    steps: [
      "Plan de management des risques : appétence, catégories (RBS), seuils, responsabilités",
      "Identification : brainstorming + checklist secteur construction, minimum 15 risques",
      "Analyse qualitative : matrice P×I, prioritisation, risques urgents vs à surveiller",
      "Analyse quantitative : simulation Monte Carlo sur le planning (utilise @RISK ou Palisade)",
      "Stratégies de réponse : pour les 5 risques majeurs, définis la stratégie et le propriétaire",
      "Réserves : calcule la réserve pour aléas (contingency) et la réserve de management",
    ],
    hints: [
      { step: 3, title: "Monte Carlo sans logiciel", hint: "Si pas accès à @RISK : utilise Python. numpy.random.triangular(optimiste, probable, pessimiste, N) simule N durées pour chaque tâche. Somme les chemins critiques → distribution du délai total. plt.hist() visualise les percentiles P50, P80, P90." },
      { step: 5, title: "Réserves de projet", hint: "Réserve pour aléas (contingency) = réponse aux risques identifiés, sous contrôle du CP. Réserve de management = réponse aux inconnues inconnues, sous contrôle du sponsor. En pratique : contingency = 10-15% du budget, management reserve = 5-10% supplémentaires." },
    ],
    resources: [
      { label: "PMI — Risk Management Standard", url: "https://www.pmi.org/pmbok-guide-standards/practice-guides/risk" },
      { label: "Monte Carlo en Python", url: "https://realpython.com/python-monte-carlo-simulation/" },
    ],
    ai_guidance: "Ce projet va au-delà de la simple liste de risques. Le tuteur peut expliquer Monte Carlo, la différence entre risques et problèmes, ou les stratégies de réponse.",
  },

  {
    track: "pmp",
    id: "pmp-int-3",
    title: "Dossier de clôture de projet",
    level: "intermediaire",
    hint_level: "medium",
    duration: "1 semaine",
    icon: "🏁",
    skills: ["clôture de projet", "leçons apprises", "transfert de livrables", "rapport final", "PMBOK"],
    description: "Sur la base d'un projet fictif terminé (système ERP déployé), rédige le dossier de clôture complet : bilan, rapport final, leçons apprises, et plan de transition vers l'exploitation.",
    learning_goal: "Maîtriser le groupe de processus de clôture PMBOK — souvent négligé mais critique pour la capitalisation et les futurs projets.",
    steps: [
      "Vérification de la complétude : tous les livrables acceptés ? Contrats fermés ? Paiements réglés ?",
      "Rapport final de projet : planifié vs réel (délais, budget, périmètre, qualité)",
      "Analyse des écarts : pourquoi le projet a dépassé de 15% le budget ? Causes documentées",
      "Leçons apprises : 10 enseignements (5 succès à répéter, 5 erreurs à éviter)",
      "Plan de transition : formation utilisateurs, documentation, support post-déploiement",
      "Archivage : liste des documents à conserver, durée de conservation, responsable",
    ],
    hints: [
      { step: 3, title: "Leçons apprises efficaces", hint: "Une bonne leçon apprise est actionnable : 'Toujours prévoir 3 semaines pour les tests UAT avec les utilisateurs, pas 1 semaine comme planifié ici' plutôt que 'Les tests ont pris trop de temps'. Le futur CP doit pouvoir l'appliquer sans te demander des explications." },
      { step: 4, title: "Critères d'acceptation des livrables", hint: "Chaque livrable doit être formellement accepté par le client/sponsor avec signature. Sans acceptation formelle, le projet n'est pas clôturé — le CP reste responsable. Documente les réserves éventuelles du client et comment elles seront traitées en période de garantie." },
    ],
    resources: [
      { label: "PMI — Project Closure Guide", url: "https://www.pmi.org/learning/library/project-closure-9355" },
      { label: "PMBOK 7 — Closing Process Group", url: "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok" },
    ],
    ai_guidance: "Le tuteur peut expliquer pourquoi la clôture formelle est critique (légalement, contractuellement) ou la différence entre clôture de phase et clôture de projet.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PMP 2026 — AVANCÉ — 2 projets
  // ══════════════════════════════════════════════════════════════════════════
  {
    track: "pmp",
    id: "pmp-adv-1",
    title: "Dossier de projet complet — transformation digitale",
    level: "avance",
    hint_level: "none",
    duration: "4-5 semaines",
    icon: "🏗️",
    skills: ["initiation", "planification", "exécution", "contrôle", "clôture", "hybride", "EVM", "risques", "parties prenantes"],
    description: "Gère un projet fictif de transformation digitale d'une entreprise de 500 employés de l'initiation à la clôture. Produis tous les livrables PMBOK 7 pour les 5 groupes de processus.",
    learning_goal: "Démontrer une maîtrise complète du management de projet — ce projet constitue un portfolio professionnel pour le jour de l'examen ou un entretien.",
    steps: [
      "Initiation : Business Case, charte de projet, identification des parties prenantes",
      "Planification : plan de management du projet, WBS, Gantt, budget, risques, communications",
      "Exécution simulée : 3 rapports d'avancement hebdomadaires avec indicateurs EVM réels",
      "Maîtrise : 2 demandes de changement, analyse d'impact, décision go/no-go documentée",
      "Clôture : rapport final, leçons apprises, archivage, bilan des parties prenantes",
      "Dossier final : PDF professionnel 30-40 pages, table des matières, tous les annexes",
    ],
    hints: [],
    resources: [
      { label: "PMI — Process Groups Practice Guide", url: "https://www.pmi.org/pmbok-guide-standards/practice-guides/process-groups" },
      { label: "PMI — Agile Practice Guide", url: "https://www.pmi.org/pmbok-guide-standards/practice-guides/agile" },
    ],
    ai_guidance: "C'est ton projet capstone PMP. Aucune aide directe — produis des livrables de qualité professionnelle. Le tuteur peut discuter des concepts théoriques ou t'aider à interpréter un cas limite.",
  },

  {
    track: "pmp",
    id: "pmp-adv-2",
    title: "Simulation d'examen PMP — 200 questions commentées",
    level: "avance",
    hint_level: "none",
    duration: "2-3 semaines",
    icon: "🎯",
    skills: ["ECO 2026", "People", "Process", "Business Environment", "agile", "hybride", "situationnel"],
    description: "Crée toi-même 200 questions situationnelles style PMP sur les 3 domaines ECO 2026 (People 33%, Process 41%, Business 26%), avec les explications des 4 options pour chaque question.",
    learning_goal: "Créer des questions oblige à comprendre en profondeur — c'est la méthode d'apprentissage la plus efficace pour l'examen PMP. Le résultat est ton propre simulateur d'examen.",
    steps: [
      "Analyse l'ECO 2026 : 35 tâches réparties sur 3 domaines — maîtrise chaque tâche",
      "Rédige 70 questions People (leadership, conflits, équipe, parties prenantes)",
      "Rédige 82 questions Process (planification, exécution, contrôle, clôture, agile/hybride)",
      "Rédige 48 questions Business Environment (bénéfices, conformité, stratégie, changements)",
      "Pour chaque question : 4 options dont 1 seule correcte, explication des 4 options",
      "Transforme en fichier CSV importable dans Anki pour révision par répétition espacée",
    ],
    hints: [],
    resources: [
      { label: "ECO 2026 — Document officiel PMI", url: "https://www.pmi.org/-/media/pmi/documents/public/pdf/certifications/project-management-professional-exam-content-outline.pdf" },
      { label: "Anki — répétition espacée", url: "https://apps.ankiweb.net/" },
      { label: "PMI — Agile Practice Guide", url: "https://www.pmi.org/pmbok-guide-standards/practice-guides/agile" },
    ],
    ai_guidance: "Ce projet transforme ta préparation — tu passes du statut d'étudiant à celui d'expert. Le tuteur peut valider si une question est bien formulée ou discuter des nuances d'une tâche ECO.",
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────────
export const PROJECT_LEVELS = {
  debutant:      { label: "Débutant",      color: "text-emerald-400", badge: "border-emerald-500/30 bg-emerald-500/5", hint_desc: "Assistance complète — astuces détaillées à chaque étape" },
  intermediaire: { label: "Intermédiaire", color: "text-amber-400",   badge: "border-amber-500/30 bg-amber-500/5",   hint_desc: "Astuces légères — oriente sans dévoiler" },
  avance:        { label: "Avancé",         color: "text-rose-400",    badge: "border-rose-500/30 bg-rose-500/5",     hint_desc: "Autonomie totale — brief seul, pas d'astuces" },
};

export function getProjectsByLevel(level) {
  return PROJECTS.filter(p => p.level === level);
}

export function getProject(id) {
  return PROJECTS.find(p => p.id === id) || null;
}
