// Bibliothèque de ressources — toutes les ressources sont gratuites, légales et vérifiées.
// Sources officielles, documentation, livres open-access et plateformes pédagogiques reconnues.

export const RESOURCE_CATEGORIES = [
  "Outils & Setup",
  "Python & Data Science",
  "Mathématiques ML",
  "Machine Learning",
  "Deep Learning & NLP",
  "MLOps & Production",
  "Cloud & Infrastructure",
  "Web Development",
  "Bases de données",
  "Certifications",
  "Robotique & RL",
];

export const RESOURCES = [
  // ── OUTILS & SETUP ──────────────────────────────────────────────────────
  {
    id: "r1",
    title: "MIT Missing Semester",
    source: "MIT (Massachusetts Institute of Technology)",
    category: "Outils & Setup",
    level: "debutant",
    type: "Cours",
    free: true,
    description: "Le cours que toute école d'informatique devrait donner en première semaine : terminal, Git, Vim, scripting, débogage. Incontournable.",
    url: "https://missing.csail.mit.edu/",
    tags: ["terminal", "git", "shell", "productivité"],
  },
  {
    id: "r2",
    title: "Pro Git",
    source: "Scott Chacon & Ben Straub",
    category: "Outils & Setup",
    level: "debutant",
    type: "Livre",
    free: true,
    description: "Le livre de référence sur Git. Gratuit en ligne. Couvre tout, des bases au workflow avancé en équipe.",
    url: "https://git-scm.com/book/en/v2",
    tags: ["git", "github", "versioning"],
  },
  {
    id: "r3",
    title: "PyCharm Documentation",
    source: "JetBrains",
    category: "Outils & Setup",
    level: "debutant",
    type: "Documentation",
    free: true,
    description: "Documentation officielle de PyCharm, l'IDE professionnel Python. Configuration venv, débogueur, tests intégrés.",
    url: "https://www.jetbrains.com/help/pycharm/",
    tags: ["ide", "python", "pycharm", "debugging"],
  },
  // ── PYTHON & DATA SCIENCE ────────────────────────────────────────────────
  {
    id: "r4",
    title: "Python Official Tutorial",
    source: "Python.org",
    category: "Python & Data Science",
    level: "debutant",
    type: "Documentation",
    free: true,
    description: "Le tutoriel officiel Python. Clair, complet, maintenu par les créateurs du langage. Référence de base.",
    url: "https://docs.python.org/3/tutorial/",
    tags: ["python", "débutant", "officiel"],
  },
  {
    id: "r5",
    title: "Kaggle Learn",
    source: "Kaggle (Google)",
    category: "Python & Data Science",
    level: "debutant",
    type: "Cours interactif",
    free: true,
    description: "Cours courts et pratiques : Python, Pandas, Feature Engineering, ML intro, SQL. Certificats gratuits à la fin de chaque cours.",
    url: "https://www.kaggle.com/learn",
    tags: ["python", "pandas", "ml", "certificat", "pratique"],
  },
  {
    id: "r6",
    title: "pandas Documentation",
    source: "pandas Development Team",
    category: "Python & Data Science",
    level: "debutant",
    type: "Documentation",
    free: true,
    description: "Documentation officielle de pandas. Guide utilisateur, API reference, exemples. La référence quand tu manipules des DataFrames.",
    url: "https://pandas.pydata.org/docs/",
    tags: ["pandas", "dataframe", "data"],
  },
  {
    id: "r7",
    title: "NumPy Documentation",
    source: "NumPy Development Team",
    category: "Python & Data Science",
    level: "debutant",
    type: "Documentation",
    free: true,
    description: "Documentation NumPy officielle. Arrays, opérations vectorisées, broadcasting, algèbre linéaire.",
    url: "https://numpy.org/doc/",
    tags: ["numpy", "arrays", "calcul"],
  },
  {
    id: "r8",
    title: "Fluent Python",
    source: "Luciano Ramalho (O'Reilly)",
    category: "Python & Data Science",
    level: "intermediaire",
    type: "Livre",
    free: false,
    description: "La référence du Python avancé : OOP, protocoles, décorateurs, typing, async. Indispensable pour progresser au-delà des bases.",
    url: "https://www.oreilly.com/library/view/fluent-python-2nd/9781492056348/",
    tags: ["python avancé", "oop", "typing", "patterns"],
    note: "Payant mais disponible en bibliothèque et sur O'Reilly Learning (abonnement).",
  },
  // ── MATHÉMATIQUES ML ─────────────────────────────────────────────────────
  {
    id: "r9",
    title: "Mathematics for Machine Learning",
    source: "Deisenroth, Faisal & Ong (Cambridge University Press)",
    category: "Mathématiques ML",
    level: "intermediaire",
    type: "Livre",
    free: true,
    description: "Livre de référence pour les maths du ML : algèbre linéaire, calcul différentiel, probabilités. PDF téléchargeable gratuitement.",
    url: "https://mml-book.github.io/",
    tags: ["maths", "algèbre", "probabilités", "gradient"],
  },
  {
    id: "r10",
    title: "OpenIntro Statistics",
    source: "OpenIntro",
    category: "Mathématiques ML",
    level: "debutant",
    type: "Livre",
    free: true,
    description: "Statistiques claires et accessibles, avec exemples pratiques. PDF gratuit. Couvre tests, distributions, régression.",
    url: "https://www.openintro.org/book/os/",
    tags: ["statistiques", "probabilités", "tests"],
  },
  {
    id: "r11",
    title: "3Blue1Brown — Essence of Linear Algebra",
    source: "3Blue1Brown (YouTube)",
    category: "Mathématiques ML",
    level: "debutant",
    type: "Vidéo",
    free: true,
    description: "Série de vidéos animées qui donnent une intuition visuelle exceptionnelle de l'algèbre linéaire. Idéal avant les formules.",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
    tags: ["algèbre linéaire", "visualisation", "intuition"],
  },
  // ── MACHINE LEARNING ─────────────────────────────────────────────────────
  {
    id: "r12",
    title: "Google ML Crash Course",
    source: "Google",
    category: "Machine Learning",
    level: "debutant",
    type: "Cours",
    free: true,
    description: "Introduction au ML par Google : concepts, exercices interactifs, TensorFlow. Parfait pour les premières semaines ML.",
    url: "https://developers.google.com/machine-learning/crash-course",
    tags: ["ml", "introduction", "google", "tensorflow"],
  },
  {
    id: "r13",
    title: "scikit-learn User Guide",
    source: "scikit-learn",
    category: "Machine Learning",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "La référence complète du ML classique en Python. Excellents exemples et explications de chaque algorithme.",
    url: "https://scikit-learn.org/stable/user_guide.html",
    tags: ["scikit-learn", "classification", "régression", "clustering"],
  },
  {
    id: "r14",
    title: "The Elements of Statistical Learning",
    source: "Hastie, Tibshirani & Friedman (Stanford)",
    category: "Machine Learning",
    level: "avance",
    type: "Livre",
    free: true,
    description: "Le livre de référence théorique du ML. Dense mais complet. PDF téléchargeable gratuitement sur le site Stanford.",
    url: "https://hastie.su.domains/ElemStatLearn/",
    tags: ["ml avancé", "statistiques", "théorie"],
  },
  // ── DEEP LEARNING & NLP ──────────────────────────────────────────────────
  {
    id: "r15",
    title: "PyTorch Tutorials",
    source: "PyTorch / Meta",
    category: "Deep Learning & NLP",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Tutoriels officiels PyTorch : tenseurs, autograd, CNN, RNN, transformers. Le meilleur point de départ pour le deep learning.",
    url: "https://pytorch.org/tutorials/",
    tags: ["pytorch", "deep learning", "neural networks"],
  },
  {
    id: "r16",
    title: "Dive into Deep Learning (D2L.ai)",
    source: "d2l.ai",
    category: "Deep Learning & NLP",
    level: "intermediaire",
    type: "Livre interactif",
    free: true,
    description: "Livre interactif sur le deep learning avec code PyTorch/TensorFlow exécutable dans le navigateur. Couvre CNN, RNN, Attention, Transformers.",
    url: "https://d2l.ai/",
    tags: ["deep learning", "interactif", "transformers", "livre"],
  },
  {
    id: "r17",
    title: "Hugging Face Learn",
    source: "Hugging Face",
    category: "Deep Learning & NLP",
    level: "intermediaire",
    type: "Cours",
    free: true,
    description: "Cours officiels Hugging Face : NLP, Computer Vision, RL, Audio, Robotique. La plateforme de référence des modèles open source.",
    url: "https://huggingface.co/learn",
    tags: ["hugging face", "nlp", "transformers", "llm", "fine-tuning"],
  },
  {
    id: "r18",
    title: "Andrej Karpathy — Neural Networks: Zero to Hero",
    source: "Andrej Karpathy (YouTube)",
    category: "Deep Learning & NLP",
    level: "intermediaire",
    type: "Vidéo",
    free: true,
    description: "Série de vidéos qui construit un LLM de zéro en Python. Le créateur de GPT-2 t'explique chaque détail. Exceptionnel.",
    url: "https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ",
    tags: ["llm", "backpropagation", "gpt", "from scratch"],
  },
  // ── MLOPS & PRODUCTION ───────────────────────────────────────────────────
  {
    id: "r19",
    title: "MLflow Documentation",
    source: "MLflow",
    category: "MLOps & Production",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Documentation MLflow : experiment tracking, model registry, deployment. Standard de l'industrie pour suivre les entraînements ML.",
    url: "https://mlflow.org/docs/latest/",
    tags: ["mlflow", "experiment tracking", "modèles"],
  },
  {
    id: "r20",
    title: "FastAPI Tutorial",
    source: "Sebastián Ramírez",
    category: "MLOps & Production",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Le tutorial officiel FastAPI. Rapide, moderne, avec validation automatique et documentation Swagger intégrée.",
    url: "https://fastapi.tiangolo.com/tutorial/",
    tags: ["fastapi", "api", "python", "rest"],
  },
  {
    id: "r21",
    title: "Docker Get Started",
    source: "Docker",
    category: "MLOps & Production",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Tutoriel officiel Docker : images, conteneurs, Compose, volumes. Base de tout déploiement moderne.",
    url: "https://docs.docker.com/get-started/",
    tags: ["docker", "conteneurs", "devops"],
  },
  {
    id: "r22",
    title: "GitHub Actions Documentation",
    source: "GitHub",
    category: "MLOps & Production",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Documentation des GitHub Actions. Automatiser tests, build et déploiement à chaque push. CI/CD intégré à GitHub.",
    url: "https://docs.github.com/en/actions",
    tags: ["ci/cd", "github", "automatisation"],
  },
  {
    id: "r23",
    title: "DeepLearning.AI — Machine Learning in Production",
    source: "DeepLearning.AI (Andrew Ng)",
    category: "MLOps & Production",
    level: "avance",
    type: "Cours",
    free: false,
    description: "Spécialisation MLOps par Andrew Ng. Couvre les pipelines ML de production, le monitoring, le data drift. Auditable gratuitement sur Coursera.",
    url: "https://www.deeplearning.ai/courses/machine-learning-engineering-for-production-mlops/",
    tags: ["mlops", "production", "andrew ng", "coursera"],
    note: "Payant pour le certificat, contenu auditable gratuitement.",
  },
  // ── CLOUD & INFRASTRUCTURE ───────────────────────────────────────────────
  {
    id: "r24",
    title: "AWS Skill Builder",
    source: "Amazon Web Services",
    category: "Cloud & Infrastructure",
    level: "intermediaire",
    type: "Cours",
    free: true,
    description: "Plateforme de formation AWS officielle. Nombreux cours gratuits sur EC2, S3, Lambda, SageMaker, et préparation aux certifications.",
    url: "https://aws.amazon.com/training/digital/",
    tags: ["aws", "cloud", "s3", "ec2", "sagemaker", "certification"],
  },
  {
    id: "r25",
    title: "AWS Well-Architected Framework",
    source: "Amazon Web Services",
    category: "Cloud & Infrastructure",
    level: "avance",
    type: "Documentation",
    free: true,
    description: "Les bonnes pratiques d'architecture cloud selon AWS : fiabilité, sécurité, performance, coûts, durabilité.",
    url: "https://aws.amazon.com/architecture/well-architected/",
    tags: ["aws", "architecture", "bonnes pratiques"],
  },
  // ── WEB DEVELOPMENT ──────────────────────────────────────────────────────
  {
    id: "r26",
    title: "MDN Web Docs",
    source: "Mozilla Foundation",
    category: "Web Development",
    level: "debutant",
    type: "Documentation",
    free: true,
    description: "LA référence absolue du web : HTML, CSS, JavaScript, Web APIs. Documentation technique de qualité, maintenue par Mozilla.",
    url: "https://developer.mozilla.org/fr/",
    tags: ["html", "css", "javascript", "référence", "mdn"],
  },
  {
    id: "r27",
    title: "JavaScript.info",
    source: "javascript.info",
    category: "Web Development",
    level: "debutant",
    type: "Cours",
    free: true,
    description: "Le meilleur tutoriel JavaScript moderne. Couvre tout, des bases aux concepts avancés (closures, prototypes, async, modules).",
    url: "https://javascript.info/",
    tags: ["javascript", "es6", "async", "dom"],
  },
  {
    id: "r28",
    title: "React Official Documentation",
    source: "Meta / React Team",
    category: "Web Development",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Documentation officielle React avec tutoriel interactif. Composants, hooks, Context, performances.",
    url: "https://react.dev/",
    tags: ["react", "hooks", "composants", "jsx"],
  },
  {
    id: "r29",
    title: "Next.js Documentation",
    source: "Vercel",
    category: "Web Development",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Documentation Next.js : App Router, Server Components, API routes, optimisation, déploiement. Le framework utilisé dans ce site.",
    url: "https://nextjs.org/docs",
    tags: ["next.js", "react", "ssr", "app router"],
  },
  {
    id: "r30",
    title: "The Odin Project",
    source: "The Odin Project",
    category: "Web Development",
    level: "debutant",
    type: "Cours",
    free: true,
    description: "Curriculum full stack complet et gratuit : HTML/CSS, JavaScript, Node.js, React. Projets concrets tout au long. Très bien structuré.",
    url: "https://www.theodinproject.com/",
    tags: ["full stack", "html", "javascript", "node", "curriculum"],
  },
  {
    id: "r31",
    title: "Tailwind CSS Documentation",
    source: "Tailwind Labs",
    category: "Web Development",
    level: "debutant",
    type: "Documentation",
    free: true,
    description: "Documentation Tailwind CSS. Classes utilitaires, configuration, plugins. Le framework CSS utilisé dans ML Academy.",
    url: "https://tailwindcss.com/docs",
    tags: ["tailwind", "css", "design", "utility-first"],
  },
  {
    id: "r32",
    title: "Node.js Documentation",
    source: "OpenJS Foundation",
    category: "Web Development",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Documentation officielle Node.js. Modules intégrés (fs, http, path), streams, events, performance.",
    url: "https://nodejs.org/en/docs",
    tags: ["node.js", "backend", "javascript serveur"],
  },
  {
    id: "r33",
    title: "Roadmap.sh — Full Stack Developer",
    source: "roadmap.sh",
    category: "Web Development",
    level: "debutant",
    type: "Référence",
    free: true,
    description: "Roadmaps visuelles et interactives pour les développeurs. Idéal pour voir le chemin complet et ne pas se perdre.",
    url: "https://roadmap.sh/full-stack",
    tags: ["roadmap", "full stack", "orientation"],
  },
  // ── BASES DE DONNÉES ─────────────────────────────────────────────────────
  {
    id: "r34",
    title: "SQLBolt",
    source: "SQLBolt",
    category: "Bases de données",
    level: "debutant",
    type: "Cours interactif",
    free: true,
    description: "Apprendre SQL par la pratique : 18 leçons interactives dans le navigateur, du SELECT simple aux requêtes avancées.",
    url: "https://sqlbolt.com/",
    tags: ["sql", "interactif", "exercices"],
  },
  {
    id: "r35",
    title: "PostgreSQL Documentation",
    source: "PostgreSQL Global Development Group",
    category: "Bases de données",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Documentation officielle PostgreSQL. Référence complète : types de données, requêtes, index, JSON, extensions.",
    url: "https://www.postgresql.org/docs/",
    tags: ["postgresql", "sql", "base de données"],
  },
  {
    id: "r36",
    title: "Prisma Documentation",
    source: "Prisma",
    category: "Bases de données",
    level: "intermediaire",
    type: "Documentation",
    free: true,
    description: "Documentation Prisma ORM. Schéma, migrations, requêtes, relations, Prisma Studio.",
    url: "https://www.prisma.io/docs",
    tags: ["prisma", "orm", "postgresql", "node"],
  },
  // ── CERTIFICATIONS ───────────────────────────────────────────────────────
  {
    id: "r37",
    title: "Kaggle Certificates",
    source: "Kaggle (Google)",
    category: "Certifications",
    level: "debutant",
    type: "Certification",
    free: true,
    description: "Certificats Kaggle Learn : Python, Pandas, Data Visualization, Intro to ML, Intermediate ML. Gratuits, rapides, reconnus.",
    url: "https://www.kaggle.com/learn",
    tags: ["certification", "kaggle", "python", "ml", "gratuit"],
  },
  {
    id: "r38",
    title: "AWS Cloud Practitioner",
    source: "Amazon Web Services",
    category: "Certifications",
    level: "debutant",
    type: "Certification",
    free: false,
    description: "Première certification AWS. Fondamentaux du cloud, services AWS. À passer après avoir déployé une application sur AWS.",
    url: "https://aws.amazon.com/certification/certified-cloud-practitioner/",
    tags: ["aws", "cloud", "certification"],
    note: "Examen payant (~100 USD). Formation préparatoire gratuite sur AWS Skill Builder.",
  },
  {
    id: "r39",
    title: "IBM Data Science Professional Certificate",
    source: "IBM / Coursera",
    category: "Certifications",
    level: "intermediaire",
    type: "Certification",
    free: false,
    description: "Spécialisation complète Data Science par IBM. Couvre Python, SQL, ML, visualisation, capstone projet. Reconnu en entreprise.",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science",
    tags: ["ibm", "data science", "coursera", "certification"],
    note: "Contenu auditable gratuitement. Certificat payant (~50 USD/mois sur Coursera).",
  },
  // ── ROBOTIQUE & RL ───────────────────────────────────────────────────────
  {
    id: "r40",
    title: "ROS2 Tutorials",
    source: "Open Robotics",
    category: "Robotique & RL",
    level: "avance",
    type: "Documentation",
    free: true,
    description: "Tutoriels officiels ROS2 (Robot Operating System). Publisher/subscriber, services, navigation. À aborder après MLOps.",
    url: "https://docs.ros.org/en/humble/Tutorials.html",
    tags: ["ros2", "robotique", "publisher", "subscriber"],
  },
  {
    id: "r41",
    title: "Spinning Up in Deep RL",
    source: "OpenAI",
    category: "Robotique & RL",
    level: "avance",
    type: "Cours",
    free: true,
    description: "Introduction au Reinforcement Learning par OpenAI. Théorie + implémentations d'algorithmes RL classiques (PPO, DDPG, SAC).",
    url: "https://spinningup.openai.com/",
    tags: ["reinforcement learning", "ppo", "openai", "rl"],
  },
];

export function getResourcesByCategory(category) {
  if (!category || category === "Tous") return RESOURCES;
  return RESOURCES.filter((r) => r.category === category);
}

export function searchResources(query) {
  const q = query.toLowerCase();
  return RESOURCES.filter(
    (r) =>
      r.title.toLowerCase().includes(q) ||
      r.description.toLowerCase().includes(q) ||
      r.tags.some((t) => t.includes(q)) ||
      r.source.toLowerCase().includes(q)
  );
}
